[package]
name = "arcweft-player-native"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
dev-capture = ["dep:png"]
macos-appkit-ime-sample = ["arcweft-desktop-native/macos-appkit-text-input"]

[dependencies]
arcweft-adapter-desktop = { path = "../arcweft-adapter-desktop" }
arcweft-audio-codec = { path = "../arcweft-audio-codec" }
arcweft-audio-core = { path = "../arcweft-audio-core" }
arcweft-audio-device-cpal = { path = "../arcweft-audio-device-cpal", features = ["native-microphone"] }
arcweft-bundle = { path = "../arcweft-bundle" }
arcweft-core = { path = "../arcweft-core" }
arcweft-desktop-contract = { path = "../arcweft-desktop-contract" }
arcweft-desktop-native = { path = "../arcweft-desktop-native" }
arcweft-host-adapter = { path = "../arcweft-host-adapter" }
arcweft-id = { path = "../arcweft-id" }
arcweft-interaction-model = { path = "../arcweft-interaction-model" }
arcweft-layout.workspace = true
arcweft-player-scene = { path = "../arcweft-player-scene" }
arcweft-player-text-input = { path = "../arcweft-player-text-input" }
arcweft-presentation = { path = "../arcweft-presentation" }
arcweft-render-native = { path = "../arcweft-render-native" }
arcweft-render-wgpu = { path = "../arcweft-render-wgpu" }
arcweft-render-text = { path = "../arcweft-render-text" }
arcweft-runtime-driver = { path = "../arcweft-runtime-driver" }
arcweft-runtime-host = { path = "../arcweft-runtime-host" }
arcweft-save.workspace = true

clap = { workspace = true, features = ["derive"] }
png = { workspace = true, optional = true }
pollster.workspace = true
num-traits = "0.2.19"
raw-window-handle.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
wgpu = { workspace = true, features = ["dx12", "metal", "vulkan"] }
winit.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
arboard = { workspace = true, features = ["wayland-data-control"] }

[target.'cfg(any(target_os = "windows", target_os = "macos"))'.dependencies]
arboard.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = ["Win32_Foundation"] }

[dev-dependencies]
arcweft-runtime-plan = { path = "../arcweft-runtime-plan" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "arcweft-player-native"
path = "src/main.rs"

[[bin]]
name = "windows-tsf-ime-sample"
path = "src/bin/windows_tsf_ime_sample.rs"

[lints]
workspace = true
