[package]
name = "arcweft-player-native"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
dev-capture = ["dep:png"]

[dependencies]
arcweft-adapter-desktop = { path = "../arcweft-adapter-desktop" }
arcweft-audio-codec = { path = "../arcweft-audio-codec" }
arcweft-audio-core = { path = "../arcweft-audio-core" }
arcweft-audio-device-cpal = { path = "../arcweft-audio-device-cpal", features = ["native-microphone"] }
arcweft-bundle = { path = "../arcweft-bundle" }
arcweft-core = { path = "../arcweft-core" }
arcweft-desktop-contract = { path = "../arcweft-desktop-contract" }
arcweft-desktop-native = { path = "../arcweft-desktop-native" }
arcweft-host-adapter = { path = "../arcweft-host-adapter" }
arcweft-interaction-model = { path = "../arcweft-interaction-model" }
arcweft-player-scene = { path = "../arcweft-player-scene" }
arcweft-presentation = { path = "../arcweft-presentation" }
arcweft-render-native = { path = "../arcweft-render-native" }
arcweft-render-wgpu = { path = "../arcweft-render-wgpu" }
arcweft-render-text = { path = "../arcweft-render-text" }
arcweft-runtime-driver = { path = "../arcweft-runtime-driver" }
arcweft-runtime-host = { path = "../arcweft-runtime-host" }

clap = { workspace = true, features = ["derive"] }
png = { workspace = true, optional = true }
pollster.workspace = true
num-traits = "0.2.19"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
wgpu = { workspace = true, features = ["dx12", "metal", "vulkan"] }
winit.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "arcweft-player-native"
path = "src/main.rs"

[lints]
workspace = true
