schema = 1
default-profile = "game.main"

[package]
id = "org.arcweft.samples.zundamon-stand-switch"
version = "0.1.0"

[build]
source-dir = "."

[profiles."game.main"]
kind = "game"
entry = "@entry.main"
source = "main.arcw"
