//! Construction schema for the expression graph generated by retained Ruby syntax.

use super::{
    HirAttachedContentApplication, HirAttachedContentApplicationFamily,
    HirAttachedContentBodyPresence, HirContentCallSemanticEvidence, HirDialogueContent,
    HirDialogueContentId, HirDialogueNode, HirDialogueNodeId, HirDialogueNodeKind, HirTextFragment,
};
use crate::expr::{
    HirCallArgument, HirCallArgumentListTerminator, HirCallCallee, HirCallChildPoison,
    HirCallChildStates, HirCallInvocation, HirCallTypeApplication, HirCallValue, HirExpr,
    HirExprKind, HirPoisonState,
};
use crate::identity::{ExprId, ScopeId, SyntheticKey, SyntheticOwner, SyntheticRole};
use crate::leaf::{
    HirLiteral, HirName, HirPath, HirPathRoot, HirPathSegment, HirPathValue, HirStringLiteral,
};
use crate::lowering::HirInvariantFailure;

/// Ephemeral lowering/validation recipe; the published value is an ordinary content call.
pub(crate) struct HirRubyDesugaring<'a> {
    owner: ExprId,
    ordinal: u32,
    scope: ScopeId,
    base: &'a str,
    reading: &'a str,
}

impl<'a> HirRubyDesugaring<'a> {
    pub(crate) const ROLES: [SyntheticRole; 3] = [
        SyntheticRole::DialogueRubyTarget,
        SyntheticRole::DialogueRubyReading,
        SyntheticRole::DialogueRubyApplication,
    ];

    pub(crate) const fn new(
        owner: ExprId,
        ordinal: u32,
        scope: ScopeId,
        base: &'a str,
        reading: &'a str,
    ) -> Self {
        Self {
            owner,
            ordinal,
            scope,
            base,
            reading,
        }
    }

    pub(crate) fn keys(&self) -> Result<[SyntheticKey; 3], HirInvariantFailure> {
        let [target, reading, application] = Self::ROLES.map(|role| {
            SyntheticKey::try_new(SyntheticOwner::Expr(self.owner), role, self.ordinal)
                .map_err(|_| HirInvariantFailure::InvalidSlotCommit)
        });
        Ok([target?, reading?, application?])
    }

    pub(crate) fn payloads(&self, ids: [ExprId; 3]) -> Result<[HirExpr; 3], HirInvariantFailure> {
        let [target, reading, application] = ids;
        let target_payload = HirExpr::try_new(
            self.scope,
            HirExprKind::Path(HirPathValue::Resolved(
                HirPath::try_new(
                    HirPathRoot::ImplicitCrate,
                    Box::new([HirPathSegment::Identifier(
                        HirName::try_new("ruby".into())
                            .map_err(|_| HirInvariantFailure::InvalidArenaCommit)?,
                    )]),
                )
                .map_err(|_| HirInvariantFailure::InvalidArenaCommit)?,
            )),
            HirPoisonState::Clean,
        )
        .map_err(|_| HirInvariantFailure::InvalidArenaCommit)?;
        let reading_payload = HirExpr::try_new(
            self.scope,
            HirExprKind::Literal(HirLiteral::String(HirStringLiteral::Value(
                self.reading.into(),
            ))),
            HirPoisonState::Clean,
        )
        .map_err(|_| HirInvariantFailure::InvalidArenaCommit)?;
        let content_id = HirDialogueContentId::new(application);
        let node = HirDialogueNodeId::try_new(content_id, 0)
            .map_err(|_| HirInvariantFailure::InvalidArenaCommit)?;
        let content = HirDialogueContent::try_new(
            content_id,
            Box::new([HirDialogueNode::new(
                node,
                HirDialogueNodeKind::Text(HirTextFragment::new(self.base.into())),
            )]),
            Box::new([]),
        )
        .map_err(|_| HirInvariantFailure::InvalidArenaCommit)?;
        let (invocation, state) = HirCallInvocation::try_new(
            HirCallCallee::value(target),
            HirCallTypeApplication::absent(),
            Box::new([HirCallArgument::Positional {
                value: HirCallValue::Present { value: reading },
            }]),
            HirCallArgumentListTerminator::Closed,
            HirCallChildStates::new(HirCallChildPoison::Clean, &[HirCallChildPoison::Clean], &[]),
            true,
        )
        .map_err(|_| HirInvariantFailure::InvalidArenaCommit)?;
        let application = HirAttachedContentApplication::try_new_with_body_presence(
            application,
            content,
            HirAttachedContentApplicationFamily::ContentCall {
                invocation,
                evidence: HirContentCallSemanticEvidence::None,
            },
            HirAttachedContentBodyPresence::Present,
        )
        .map_err(|_| HirInvariantFailure::InvalidArenaCommit)?;
        let application_payload = HirExpr::try_new(
            self.scope,
            HirExprKind::AttachedContentApplication(application),
            state,
        )
        .map_err(|_| HirInvariantFailure::InvalidArenaCommit)?;
        Ok([target_payload, reading_payload, application_payload])
    }
}
