[package]
name = "arcweft-character-view"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
arcweft-character = { path = "../arcweft-character" }
arcweft-image = { path = "../arcweft-image" }
arcweft-presentation = { path = "../arcweft-presentation" }
arcweft-view = { path = "../arcweft-view" }
thiserror.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true
