[package]
name = "arcweft-lang-syntax"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arcweft-id = { workspace = true }
arcweft-source = { workspace = true }
blake3.workspace = true
rowan.workspace = true
thiserror.workspace = true

[dev-dependencies]
arcweft-presentation = { workspace = true }
serde.workspace = true
trybuild.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true
