[package]
name = "arcweft-lang-syntax"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arcweft-source = { path = "../arcweft-source" }
blake3.workspace = true
rowan.workspace = true
thiserror.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true
