[package]
name = "arcweft-render-text"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arcweft-core = { path = "../arcweft-core" }
arcweft-dialogue = { path = "../arcweft-dialogue" }
arcweft-presentation = { path = "../arcweft-presentation" }
arcweft-view = { path = "../arcweft-view" }

serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true

[lints]
workspace = true
