//! Stable semantic tags for the closed Agent field inventory.

use super::RuntimeAgentField;

impl RuntimeAgentField {
    pub const ALL: &'static [Self] = &[
        Self::ObservationTick,
        Self::ObservationFrameId,
        Self::ObservationStateHash,
        Self::ObservationRenderHash,
        Self::ObservationActions,
        Self::ObservationObjects,
        Self::ObservationSignals,
        Self::ObservedObjectId,
        Self::ObservedObjectParentId,
        Self::ObservedObjectEntity,
        Self::ObservedObjectLayer,
        Self::ObservedObjectRole,
        Self::ObservedObjectText,
        Self::ObservedObjectVisible,
        Self::ObservedObjectEnabled,
        Self::ObservedObjectBoundingBox,
        Self::BoundingBoxSpace,
        Self::BoundingBoxX,
        Self::BoundingBoxY,
        Self::BoundingBoxWidth,
        Self::BoundingBoxHeight,
        Self::ActionId,
        Self::ActionTarget,
        Self::ActionName,
        Self::ActionKind,
        Self::ActionEnabled,
        Self::ActionResultAccepted,
        Self::ActionResultBeforeTick,
        Self::ActionResultAfterTick,
        Self::ActionResultBeforeStateHash,
        Self::ActionResultAfterStateHash,
        Self::CaptureReferenceUri,
        Self::CaptureReferenceContentHash,
        Self::CaptureReferenceMediaType,
        Self::CaptureReferenceByteLen,
        Self::ResourceUri,
        Self::ResourceKind,
        Self::ResourceMimeType,
        Self::ResourceHash,
        Self::ResourceBody,
        Self::BinaryBodyEncoding,
        Self::BinaryBodyData,
        Self::EntityMetadataId,
        Self::EntityMetadataKind,
        Self::EntityMetadataSemanticHash,
        Self::EntityMetadataSource,
        Self::SourceAnchorPath,
        Self::SourceAnchorStartByte,
        Self::SourceAnchorEndByte,
        Self::SourceAnchorStart,
        Self::SourceAnchorEnd,
        Self::SourcePositionLine,
        Self::SourcePositionColumn,
        Self::ProjectGraphNeighborhoodRoot,
        Self::ProjectGraphNeighborhoodNodeCount,
        Self::ProjectGraphNeighborhoodEdgeCount,
        Self::ProjectGraphNeighborhoodSymbols,
        Self::ProjectGraphNeighborhoodEdges,
        Self::ProjectGraphSymbolSymbolId,
        Self::ProjectGraphSymbolId,
        Self::ProjectGraphSymbolKind,
        Self::ProjectGraphSymbolSemanticHash,
        Self::ProjectGraphSymbolSummary,
        Self::ProjectGraphSymbolFlowControl,
        Self::ProjectGraphSymbolProjectSummary,
        Self::ProjectFlowControlHasDynamicControl,
        Self::ProjectFlowControlStaticGotoCount,
        Self::ProjectFlowControlDynamicGotoCount,
        Self::ProjectFlowControlBranchCount,
        Self::ProjectFlowControlLoopCount,
        Self::ProjectFlowControlAwaitCount,
        Self::ProjectFlowControlThreadCount,
        Self::ProjectFlowControlSelectBranchCount,
        Self::ProjectGraphSummaryEntityCount,
        Self::ProjectGraphSummaryAgentActionCount,
        Self::ProjectGraphSummaryProjectCallableCount,
        Self::ProjectGraphSummaryRelationCount,
        Self::ProjectGraphSummaryDependencyEdgeCount,
        Self::ProjectGraphSummaryDynamicControlFlowCount,
        Self::ProjectGraphSummaryDebugQueryCount,
        Self::ProjectGraphEdgeFromSymbolId,
        Self::ProjectGraphEdgeToSymbolId,
        Self::ProjectGraphEdgeKind,
        Self::ReferenceId,
        Self::ReferenceFamily,
        Self::ReferenceName,
        Self::ViewportX,
        Self::ViewportY,
    ];

    /// Stable semantic tag. Removed unreleased coordinates leave no reader or
    /// tombstone variant; surviving identities retain their assigned tags.
    pub const fn semantic_tag(self) -> u16 {
        match self {
            Self::ObservationTick => 0,
            Self::ObservationFrameId => 1,
            Self::ObservationStateHash => 2,
            Self::ObservationRenderHash => 3,
            Self::ObservationActions => 4,
            Self::ObservationObjects => 5,
            Self::ObservationSignals => 6,
            Self::ObservedObjectId => 7,
            Self::ObservedObjectParentId => 8,
            Self::ObservedObjectEntity => 9,
            Self::ObservedObjectLayer => 10,
            Self::ObservedObjectRole => 11,
            Self::ObservedObjectText => 12,
            Self::ObservedObjectVisible => 13,
            Self::ObservedObjectEnabled => 14,
            Self::ObservedObjectBoundingBox => 15,
            Self::BoundingBoxSpace => 16,
            Self::BoundingBoxX => 17,
            Self::BoundingBoxY => 18,
            Self::BoundingBoxWidth => 19,
            Self::BoundingBoxHeight => 20,
            Self::ActionId => 21,
            Self::ActionTarget => 22,
            Self::ActionName => 23,
            Self::ActionKind => 24,
            Self::ActionEnabled => 25,
            Self::ActionResultAccepted => 26,
            Self::ActionResultBeforeTick => 27,
            Self::ActionResultAfterTick => 28,
            Self::ActionResultBeforeStateHash => 29,
            Self::ActionResultAfterStateHash => 30,
            Self::CaptureReferenceUri => 31,
            Self::CaptureReferenceContentHash => 32,
            Self::CaptureReferenceMediaType => 33,
            Self::CaptureReferenceByteLen => 34,
            Self::ResourceUri => 35,
            Self::ResourceKind => 36,
            Self::ResourceMimeType => 37,
            Self::ResourceHash => 38,
            Self::ResourceBody => 39,
            Self::BinaryBodyEncoding => 40,
            Self::BinaryBodyData => 41,
            Self::EntityMetadataId => 46,
            Self::EntityMetadataKind => 47,
            Self::EntityMetadataSemanticHash => 48,
            Self::EntityMetadataSource => 49,
            Self::SourceAnchorPath => 51,
            Self::SourceAnchorStartByte => 52,
            Self::SourceAnchorEndByte => 53,
            Self::SourceAnchorStart => 54,
            Self::SourceAnchorEnd => 55,
            Self::SourcePositionLine => 56,
            Self::SourcePositionColumn => 57,
            Self::ProjectGraphNeighborhoodRoot => 58,
            Self::ProjectGraphNeighborhoodNodeCount => 59,
            Self::ProjectGraphNeighborhoodEdgeCount => 60,
            Self::ProjectGraphNeighborhoodSymbols => 61,
            Self::ProjectGraphNeighborhoodEdges => 62,
            Self::ProjectGraphSymbolSymbolId => 63,
            Self::ProjectGraphSymbolId => 64,
            Self::ProjectGraphSymbolKind => 65,
            Self::ProjectGraphSymbolSemanticHash => 66,
            Self::ProjectGraphSymbolSummary => 67,
            Self::ProjectGraphSymbolFlowControl => 70,
            Self::ProjectFlowControlHasDynamicControl => 71,
            Self::ProjectGraphSymbolProjectSummary => 72,
            Self::ProjectGraphSummaryEntityCount => 73,
            Self::ProjectGraphSummaryAgentActionCount => 74,
            Self::ProjectGraphSummaryProjectCallableCount => 75,
            Self::ProjectGraphSummaryRelationCount => 76,
            Self::ProjectGraphSummaryDependencyEdgeCount => 77,
            Self::ProjectGraphSummaryDynamicControlFlowCount => 78,
            Self::ProjectGraphSummaryDebugQueryCount => 79,
            Self::ProjectFlowControlStaticGotoCount => 80,
            Self::ProjectFlowControlDynamicGotoCount => 81,
            Self::ProjectFlowControlBranchCount => 82,
            Self::ProjectFlowControlLoopCount => 83,
            Self::ProjectFlowControlAwaitCount => 84,
            Self::ProjectFlowControlThreadCount => 85,
            Self::ProjectFlowControlSelectBranchCount => 86,
            Self::ProjectGraphEdgeFromSymbolId => 87,
            Self::ProjectGraphEdgeToSymbolId => 88,
            Self::ProjectGraphEdgeKind => 89,
            Self::ReferenceId => 90,
            Self::ReferenceFamily => 91,
            Self::ReferenceName => 92,
            Self::ViewportX => 93,
            Self::ViewportY => 94,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::RuntimeAgentField;
    use std::collections::BTreeSet;

    #[test]
    fn runtime_agent_field_semantic_tags_are_unique() {
        let tags = RuntimeAgentField::ALL
            .iter()
            .copied()
            .map(RuntimeAgentField::semantic_tag)
            .collect::<BTreeSet<_>>();
        assert_eq!(tags.len(), RuntimeAgentField::ALL.len());
    }
}
