//! Stable semantic tags for the closed Agent field inventory.

use super::RuntimeAgentField;

impl RuntimeAgentField {
    pub const ALL: &'static [Self] = &[
        Self::ObservationTick,
        Self::ObservationFrameId,
        Self::ObservationStateHash,
        Self::ObservationRenderHash,
        Self::ObservationActions,
        Self::ObservationObjects,
        Self::ObservationSignals,
        Self::ObservedObjectId,
        Self::ObservedObjectParentId,
        Self::ObservedObjectEntity,
        Self::ObservedObjectLayer,
        Self::ObservedObjectRole,
        Self::ObservedObjectText,
        Self::ObservedObjectVisible,
        Self::ObservedObjectEnabled,
        Self::ObservedObjectBoundingBox,
        Self::BoundingBoxSpace,
        Self::BoundingBoxX,
        Self::BoundingBoxY,
        Self::BoundingBoxWidth,
        Self::BoundingBoxHeight,
        Self::ActionId,
        Self::ActionTarget,
        Self::ActionName,
        Self::ActionKind,
        Self::ActionEnabled,
        Self::ActionResultAccepted,
        Self::ActionResultBeforeTick,
        Self::ActionResultAfterTick,
        Self::ActionResultBeforeStateHash,
        Self::ActionResultAfterStateHash,
        Self::CaptureReferenceUri,
        Self::CaptureReferenceContentHash,
        Self::CaptureReferenceMediaType,
        Self::CaptureReferenceByteLen,
        Self::ResourceUri,
        Self::ResourceKind,
        Self::ResourceMimeType,
        Self::ResourceHash,
        Self::ResourceBody,
        Self::ResourceBodyKind,
        Self::ResourceBodyJson,
        Self::ResourceBodyText,
        Self::ResourceBodyBase64,
        Self::ResourceBodyEncoding,
        Self::ResourceBodyValue,
        Self::EntityMetadataId,
        Self::EntityMetadataKind,
        Self::EntityMetadataSemanticHash,
        Self::EntityMetadataSource,
        Self::SourceAnchorHasSource,
        Self::SourceAnchorPath,
        Self::SourceAnchorStartByte,
        Self::SourceAnchorEndByte,
        Self::SourceAnchorStartLine,
        Self::SourceAnchorStartColumn,
        Self::SourceAnchorEndLine,
        Self::SourceAnchorEndColumn,
        Self::ProjectGraphNeighborhoodRoot,
        Self::ProjectGraphNeighborhoodNodeCount,
        Self::ProjectGraphNeighborhoodEdgeCount,
        Self::ProjectGraphNeighborhoodSymbols,
        Self::ProjectGraphNeighborhoodEdges,
        Self::ProjectGraphSymbolSymbolId,
        Self::ProjectGraphSymbolId,
        Self::ProjectGraphSymbolKind,
        Self::ProjectGraphSymbolSemanticHash,
        Self::ProjectGraphSymbolSummary,
        Self::ProjectGraphSymbolHasEntity,
        Self::ProjectGraphSymbolHasSemanticHash,
        Self::ProjectGraphSymbolHasFlowControl,
        Self::ProjectGraphSymbolHasDynamicControl,
        Self::ProjectGraphSymbolHasProjectSummary,
        Self::ProjectGraphSymbolEntityCount,
        Self::ProjectGraphSymbolAgentActionCount,
        Self::ProjectGraphSymbolProjectCallableCount,
        Self::ProjectGraphSymbolRelationCount,
        Self::ProjectGraphSymbolDependencyEdgeCount,
        Self::ProjectGraphSymbolDynamicControlFlowCount,
        Self::ProjectGraphSymbolDebugQueryCount,
        Self::ProjectGraphSymbolStaticGotoCount,
        Self::ProjectGraphSymbolDynamicGotoCount,
        Self::ProjectGraphSymbolBranchCount,
        Self::ProjectGraphSymbolLoopCount,
        Self::ProjectGraphSymbolAwaitCount,
        Self::ProjectGraphSymbolThreadCount,
        Self::ProjectGraphSymbolSelectBranchCount,
        Self::ProjectGraphEdgeFromSymbolId,
        Self::ProjectGraphEdgeToSymbolId,
        Self::ProjectGraphEdgeKind,
        Self::ReferenceId,
        Self::ReferenceFamily,
        Self::ReferenceName,
        Self::ViewportX,
        Self::ViewportY,
    ];

    /// Stable semantic tag in declaration order.
    pub const fn semantic_tag(self) -> u16 {
        match self {
            Self::ObservationTick => 0,
            Self::ObservationFrameId => 1,
            Self::ObservationStateHash => 2,
            Self::ObservationRenderHash => 3,
            Self::ObservationActions => 4,
            Self::ObservationObjects => 5,
            Self::ObservationSignals => 6,
            Self::ObservedObjectId => 7,
            Self::ObservedObjectParentId => 8,
            Self::ObservedObjectEntity => 9,
            Self::ObservedObjectLayer => 10,
            Self::ObservedObjectRole => 11,
            Self::ObservedObjectText => 12,
            Self::ObservedObjectVisible => 13,
            Self::ObservedObjectEnabled => 14,
            Self::ObservedObjectBoundingBox => 15,
            Self::BoundingBoxSpace => 16,
            Self::BoundingBoxX => 17,
            Self::BoundingBoxY => 18,
            Self::BoundingBoxWidth => 19,
            Self::BoundingBoxHeight => 20,
            Self::ActionId => 21,
            Self::ActionTarget => 22,
            Self::ActionName => 23,
            Self::ActionKind => 24,
            Self::ActionEnabled => 25,
            Self::ActionResultAccepted => 26,
            Self::ActionResultBeforeTick => 27,
            Self::ActionResultAfterTick => 28,
            Self::ActionResultBeforeStateHash => 29,
            Self::ActionResultAfterStateHash => 30,
            Self::CaptureReferenceUri => 31,
            Self::CaptureReferenceContentHash => 32,
            Self::CaptureReferenceMediaType => 33,
            Self::CaptureReferenceByteLen => 34,
            Self::ResourceUri => 35,
            Self::ResourceKind => 36,
            Self::ResourceMimeType => 37,
            Self::ResourceHash => 38,
            Self::ResourceBody => 39,
            Self::ResourceBodyKind => 40,
            Self::ResourceBodyJson => 41,
            Self::ResourceBodyText => 42,
            Self::ResourceBodyBase64 => 43,
            Self::ResourceBodyEncoding => 44,
            Self::ResourceBodyValue => 45,
            Self::EntityMetadataId => 46,
            Self::EntityMetadataKind => 47,
            Self::EntityMetadataSemanticHash => 48,
            Self::EntityMetadataSource => 49,
            Self::SourceAnchorHasSource => 50,
            Self::SourceAnchorPath => 51,
            Self::SourceAnchorStartByte => 52,
            Self::SourceAnchorEndByte => 53,
            Self::SourceAnchorStartLine => 54,
            Self::SourceAnchorStartColumn => 55,
            Self::SourceAnchorEndLine => 56,
            Self::SourceAnchorEndColumn => 57,
            Self::ProjectGraphNeighborhoodRoot => 58,
            Self::ProjectGraphNeighborhoodNodeCount => 59,
            Self::ProjectGraphNeighborhoodEdgeCount => 60,
            Self::ProjectGraphNeighborhoodSymbols => 61,
            Self::ProjectGraphNeighborhoodEdges => 62,
            Self::ProjectGraphSymbolSymbolId => 63,
            Self::ProjectGraphSymbolId => 64,
            Self::ProjectGraphSymbolKind => 65,
            Self::ProjectGraphSymbolSemanticHash => 66,
            Self::ProjectGraphSymbolSummary => 67,
            Self::ProjectGraphSymbolHasEntity => 68,
            Self::ProjectGraphSymbolHasSemanticHash => 69,
            Self::ProjectGraphSymbolHasFlowControl => 70,
            Self::ProjectGraphSymbolHasDynamicControl => 71,
            Self::ProjectGraphSymbolHasProjectSummary => 72,
            Self::ProjectGraphSymbolEntityCount => 73,
            Self::ProjectGraphSymbolAgentActionCount => 74,
            Self::ProjectGraphSymbolProjectCallableCount => 75,
            Self::ProjectGraphSymbolRelationCount => 76,
            Self::ProjectGraphSymbolDependencyEdgeCount => 77,
            Self::ProjectGraphSymbolDynamicControlFlowCount => 78,
            Self::ProjectGraphSymbolDebugQueryCount => 79,
            Self::ProjectGraphSymbolStaticGotoCount => 80,
            Self::ProjectGraphSymbolDynamicGotoCount => 81,
            Self::ProjectGraphSymbolBranchCount => 82,
            Self::ProjectGraphSymbolLoopCount => 83,
            Self::ProjectGraphSymbolAwaitCount => 84,
            Self::ProjectGraphSymbolThreadCount => 85,
            Self::ProjectGraphSymbolSelectBranchCount => 86,
            Self::ProjectGraphEdgeFromSymbolId => 87,
            Self::ProjectGraphEdgeToSymbolId => 88,
            Self::ProjectGraphEdgeKind => 89,
            Self::ReferenceId => 90,
            Self::ReferenceFamily => 91,
            Self::ReferenceName => 92,
            Self::ViewportX => 93,
            Self::ViewportY => 94,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::RuntimeAgentField;
    use std::collections::BTreeSet;

    #[test]
    fn runtime_agent_field_semantic_tags_are_unique() {
        let tags = RuntimeAgentField::ALL
            .iter()
            .copied()
            .map(RuntimeAgentField::semantic_tag)
            .collect::<BTreeSet<_>>();
        assert_eq!(tags.len(), RuntimeAgentField::ALL.len());
    }
}
