//! Resolved dialogue display frame and source map.

use crate::{
    DialogueHostEvent, RichTextControl, RichTextPresentation, RichTextStyle,
    RichTextStyleContribution,
};
use arcweft_character::id::{CharacterId, CharacterLookId};
use arcweft_core::entry::RuntimeValueDigest;
use arcweft_core::plan::RuntimeLineId;
use arcweft_dialogue::{
    CharacterDialogueCleanupValue, CharacterDialogueCustomFieldId, CharacterDialogueCustomValue,
    CharacterDialogueFocusValue, CharacterDialogueHookValue, CharacterDialoguePortraitValue,
    CharacterDialogueStageValue, CharacterDialogueVoice, DialogueLocaleId, InlineFailurePolicy,
    InlineTextFailure,
};
use arcweft_id::TextKey;
use arcweft_presentation::fx::FxApplication;
use arcweft_view::ViewId;
use serde::{Deserialize, Deserializer, Serialize};
use std::collections::BTreeMap;

/// Typed character presentation metadata resolved by the accepted character
/// catalog. The display name is presentation data, never line identity.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct DialoguePresentationCharacter {
    pub id: CharacterId,
    pub display_name: String,
}

/// Dynamic effective `CharacterDialogue` configuration for one frame.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct CharacterDialoguePresentationConfig {
    pub view: ViewId,
    pub voice: Option<CharacterDialogueVoice>,
    pub look: Option<CharacterLookId>,
    pub stage: Option<CharacterDialogueStageValue>,
    pub portrait: Option<CharacterDialoguePortraitValue>,
    pub focus: Option<CharacterDialogueFocusValue>,
    pub cleanup: Option<CharacterDialogueCleanupValue>,
    pub source_locale: Option<DialogueLocaleId>,
    pub hooks: Vec<CharacterDialogueHookValue>,
    pub inline_failure: InlineFailurePolicy,
    pub custom: BTreeMap<CharacterDialogueCustomFieldId, CharacterDialogueCustomValue>,
    pub config_digest: RuntimeValueDigest,
}

/// One resolved frame generated by a player adapter.
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct LineDisplayFrame {
    pub line: RuntimeLineId,
    pub character: DialoguePresentationCharacter,
    pub text_key: TextKey,
    pub effective: CharacterDialoguePresentationConfig,
    pub text: String,
    pub base_styles: Vec<RichTextStyle>,
    pub style_contributions: Vec<RichTextStyleContribution>,
    pub nodes: Vec<crate::RichTextNode>,
    pub display_map: RichTextDisplayMap,
    pub host_events: Vec<DialogueHostEvent>,
    pub inline_failures: Vec<InlineTextFailure>,
    pub unresolved: Vec<String>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct LineDisplayFrameWire {
    line: RuntimeLineId,
    character: DialoguePresentationCharacter,
    text_key: TextKey,
    effective: CharacterDialoguePresentationConfig,
    text: String,
    base_styles: Vec<RichTextStyle>,
    style_contributions: Vec<RichTextStyleContribution>,
    nodes: Vec<crate::RichTextNode>,
    display_map: RichTextDisplayMap,
    host_events: Vec<DialogueHostEvent>,
    inline_failures: Vec<InlineTextFailure>,
    unresolved: Vec<String>,
}

impl<'de> Deserialize<'de> for LineDisplayFrame {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let wire = LineDisplayFrameWire::deserialize(deserializer)?;
        let frame = Self {
            line: wire.line,
            character: wire.character,
            text_key: wire.text_key,
            effective: wire.effective,
            text: wire.text,
            base_styles: wire.base_styles,
            style_contributions: wire.style_contributions,
            nodes: wire.nodes,
            display_map: wire.display_map,
            host_events: wire.host_events,
            inline_failures: wire.inline_failures,
            unresolved: wire.unresolved,
        };
        frame.validate().map_err(serde::de::Error::custom)?;
        Ok(frame)
    }
}

/// Mapping from resolved display text back to authored rich-text nodes.
#[derive(Clone, Debug, Default, Deserialize, PartialEq, Serialize)]
pub struct RichTextDisplayMap {
    pub text_runs: Vec<RichTextTextRun>,
    pub ruby_annotations: Vec<RichTextRubyAnnotation>,
    pub controls: Vec<RichTextControlMarker>,
    pub host_events: Vec<RichTextHostEventMarker>,
}

/// Half-open UTF-8 byte range.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextRange {
    pub start: usize,
    pub end: usize,
}

impl RichTextRange {
    #[must_use]
    pub const fn new(start: usize, end: usize) -> Self {
        Self { start, end }
    }
}

/// One resolved visible text run.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextTextRun {
    pub range: RichTextRange,
    pub source: RichTextTextSource,
    pub node_index: usize,
    pub styles: Vec<RichTextStyle>,
    #[serde(default)]
    pub presentation: RichTextPresentation,
}

/// Source category for a resolved visible text run.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum RichTextTextSource {
    Text,
    Interpolation,
    InterpolationFallback,
    RubyBase,
    ControlHardBreak,
    ControlRaw,
}

/// Ruby annotation attached to a resolved base text range.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextRubyAnnotation {
    pub base_range: RichTextRange,
    pub ruby: String,
    pub node_index: usize,
    pub styles: Vec<RichTextStyle>,
    #[serde(default)]
    pub presentation: RichTextPresentation,
}

/// Control node marker in the resolved display stream.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextControlMarker {
    pub node_index: usize,
    /// UTF-8 byte offset immediately before this control executes.
    pub text_offset: usize,
    pub control: RichTextControl,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub range: Option<RichTextRange>,
}

/// Host event marker in authored node order.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct RichTextHostEventMarker {
    pub node_index: usize,
    /// UTF-8 byte offset at which this event becomes reachable.
    pub text_offset: usize,
    pub event_index: usize,
    pub event: DialogueHostEvent,
}

impl LineDisplayFrame {
    /// Returns each active typed Fx application once in authored style-start order.
    pub fn fx_applications(&self) -> impl Iterator<Item = &FxApplication> {
        self.base_styles
            .iter()
            .chain(self.nodes.iter().filter_map(|node| match node {
                crate::RichTextNode::StyleStart { style } => Some(style),
                _ => None,
            }))
            .filter_map(|style| match style {
                RichTextStyle::Fx { application } => Some(application),
                _ => None,
            })
    }
}

#[cfg(test)]
mod serde_tests {
    use super::*;
    use crate::{RichTextNode, RichTextTextSource};

    fn frame() -> LineDisplayFrame {
        let text = "Hello".to_owned();
        LineDisplayFrame {
            line: RuntimeLineId::from_runtime_line_value("say.test.001")
                .expect("runtime line identity"),
            character: DialoguePresentationCharacter {
                id: CharacterId::try_new("character.alice").expect("character identity"),
                display_name: "Alice".to_owned(),
            },
            text_key: TextKey::try_new("text.test.001").expect("text key"),
            effective: CharacterDialoguePresentationConfig {
                view: ViewId::try_new("view.dialogue.test").expect("View identity"),
                voice: None,
                look: None,
                stage: None,
                portrait: None,
                focus: None,
                cleanup: None,
                source_locale: None,
                hooks: Vec::new(),
                inline_failure: InlineFailurePolicy::FailLine,
                custom: BTreeMap::new(),
                config_digest: RuntimeValueDigest::ZERO,
            },
            text,
            base_styles: Vec::new(),
            style_contributions: Vec::new(),
            nodes: vec![RichTextNode::Text {
                text: "Hello".to_owned(),
            }],
            display_map: RichTextDisplayMap {
                text_runs: vec![RichTextTextRun {
                    range: RichTextRange::new(0, 5),
                    source: RichTextTextSource::Text,
                    node_index: 0,
                    styles: Vec::new(),
                    presentation: RichTextPresentation::default(),
                }],
                ..RichTextDisplayMap::default()
            },
            host_events: Vec::new(),
            inline_failures: Vec::new(),
            unresolved: Vec::new(),
        }
    }

    #[test]
    fn line_display_frame_round_trips_the_final_typed_wire() {
        let frame = frame();
        frame.validate().expect("fixture is structurally valid");
        let encoded = serde_json::to_vec(&frame).expect("frame serializes");
        let decoded = serde_json::from_slice::<LineDisplayFrame>(&encoded)
            .expect("validated frame deserializes");
        assert_eq!(decoded, frame);
    }

    #[test]
    fn line_display_frame_wire_rejects_invalid_ranges_and_removed_flat_fields() {
        let mut invalid_range = serde_json::to_value(frame()).expect("frame serializes");
        invalid_range["display_map"]["text_runs"][0]["range"]["end"] = 100.into();
        assert!(serde_json::from_value::<LineDisplayFrame>(invalid_range).is_err());

        let mut removed_flat_field = serde_json::to_value(frame()).expect("frame serializes");
        removed_flat_field["callee"] = "alice".into();
        assert!(serde_json::from_value::<LineDisplayFrame>(removed_flat_field).is_err());
    }
}
