//! Resolved dialogue display frame and source map.

use crate::{
    DialogueHostEvent, RichTextControl, RichTextPresentation, RichTextStyle,
    RichTextStyleContribution,
};
use arcweft_character::id::{CharacterId, CharacterLookId};
use arcweft_core::entry::RuntimeValueDigest;
use arcweft_core::plan::RuntimeLineId;
use arcweft_core::value::RuntimeDialogueContentValue;
use arcweft_dialogue::{
    CharacterDialogueCleanupValue, CharacterDialogueCustomFieldId, CharacterDialogueCustomValue,
    CharacterDialogueFocusValue, CharacterDialogueHookValue, CharacterDialoguePortraitValue,
    CharacterDialogueStageValue, CharacterDialogueVoice, DialogueLocaleId, InlineFailurePolicy,
    InlineTextFailure,
};
use arcweft_id::TextKey;
use arcweft_presentation::fx::FxApplication;
use arcweft_view::ViewId;
use serde::{Deserialize, Deserializer, Serialize};
use std::collections::BTreeMap;
use thiserror::Error;

/// Typed character presentation metadata resolved by the accepted character
/// catalog. The display name is presentation data, never line identity.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct DialoguePresentationCharacter {
    pub id: CharacterId,
    pub display_name: String,
}

/// Dynamic effective `CharacterDialogue` configuration for one frame.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct CharacterDialoguePresentationConfig {
    pub view: ViewId,
    pub voice: Option<CharacterDialogueVoice>,
    pub look: Option<CharacterLookId>,
    pub stage: Option<CharacterDialogueStageValue>,
    pub portrait: Option<CharacterDialoguePortraitValue>,
    pub focus: Option<CharacterDialogueFocusValue>,
    pub cleanup: Option<CharacterDialogueCleanupValue>,
    pub source_locale: Option<DialogueLocaleId>,
    pub hooks: Vec<CharacterDialogueHookValue>,
    pub inline_failure: InlineFailurePolicy,
    pub custom: BTreeMap<CharacterDialogueCustomFieldId, CharacterDialogueCustomValue>,
    pub config_digest: RuntimeValueDigest,
}

/// One resolved frame generated by a player adapter.
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct LineDisplayFrame {
    pub line: RuntimeLineId,
    pub character: DialoguePresentationCharacter,
    pub text_key: TextKey,
    pub effective: CharacterDialoguePresentationConfig,
    pub text: String,
    pub base_styles: Vec<RichTextStyle>,
    pub style_contributions: Vec<RichTextStyleContribution>,
    pub nodes: Vec<ResolvedRichTextNode>,
    pub display_map: RichTextDisplayMap,
    pub host_events: Vec<DialogueHostEvent>,
    pub inline_failures: Vec<InlineTextFailure>,
    pub unresolved: Vec<String>,
    /// Exact Content envelope retained for the authored DialogueView value.
    /// Every resolved dialogue frame carries the producer-validated envelope;
    /// callers never need to infer content from the rendered text.
    pub content: RuntimeDialogueContentValue,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct LineDisplayFrameWire {
    line: RuntimeLineId,
    character: DialoguePresentationCharacter,
    text_key: TextKey,
    effective: CharacterDialoguePresentationConfig,
    text: String,
    base_styles: Vec<RichTextStyle>,
    style_contributions: Vec<RichTextStyleContribution>,
    nodes: Vec<ResolvedRichTextNode>,
    display_map: RichTextDisplayMap,
    host_events: Vec<DialogueHostEvent>,
    inline_failures: Vec<InlineTextFailure>,
    unresolved: Vec<String>,
    content: RuntimeDialogueContentValue,
}

impl<'de> Deserialize<'de> for LineDisplayFrame {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let wire = LineDisplayFrameWire::deserialize(deserializer)?;
        let frame = Self {
            line: wire.line,
            character: wire.character,
            text_key: wire.text_key,
            effective: wire.effective,
            text: wire.text,
            base_styles: wire.base_styles,
            style_contributions: wire.style_contributions,
            nodes: wire.nodes,
            display_map: wire.display_map,
            host_events: wire.host_events,
            inline_failures: wire.inline_failures,
            unresolved: wire.unresolved,
            content: wire.content,
        };
        frame.validate().map_err(serde::de::Error::custom)?;
        Ok(frame)
    }
}

/// Mapping from resolved display text back to authored rich-text nodes.
#[derive(Clone, Debug, Default, Deserialize, PartialEq, Serialize)]
pub struct RichTextDisplayMap {
    /// Number of resolved authored nodes in preorder, including structural
    /// wrappers and nodes whose interpolation was discarded.
    pub source_node_count: RichTextNodeCount,
    pub text_runs: Vec<RichTextTextRun>,
    pub ruby_annotations: Vec<RichTextRubyAnnotation>,
    pub controls: Vec<RichTextControlMarker>,
    pub host_events: Vec<RichTextHostEventMarker>,
}

/// Zero-based preorder index of one resolved authored rich-text node.
///
/// Display-map indices are a wire/data boundary, so they deliberately use a
/// fixed-width integer rather than the host-dependent `usize` type.
#[derive(
    Clone, Copy, Debug, Default, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize,
)]
#[serde(transparent)]
pub struct RichTextNodeIndex(u32);

impl RichTextNodeIndex {
    #[must_use]
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    #[must_use]
    pub const fn get(self) -> u32 {
        self.0
    }

    #[must_use]
    pub const fn as_usize(self) -> usize {
        self.0 as usize
    }

    #[must_use]
    pub const fn index(self) -> usize {
        self.as_usize()
    }

    #[must_use]
    pub fn from_zero_based(index: usize) -> Option<Self> {
        u32::try_from(index).ok().map(Self)
    }

    pub fn try_from_index(index: usize) -> Result<Self, RichTextNodeIndexOverflow> {
        u32::try_from(index)
            .map(Self)
            .map_err(|_| RichTextNodeIndexOverflow { index })
    }
}

impl From<RichTextNodeIndex> for usize {
    fn from(value: RichTextNodeIndex) -> Self {
        value.as_usize()
    }
}

impl TryFrom<usize> for RichTextNodeIndex {
    type Error = RichTextNodeIndexOverflow;

    fn try_from(value: usize) -> Result<Self, Self::Error> {
        Self::try_from_index(value)
    }
}

/// Failure to represent a host node index in the stable display-map wire.
#[derive(Clone, Copy, Debug, Error, Eq, PartialEq)]
#[error("rich-text node index {index} exceeds u32::MAX")]
pub struct RichTextNodeIndexOverflow {
    pub index: usize,
}

/// Number of resolved authored rich-text nodes in preorder.
#[derive(
    Clone, Copy, Debug, Default, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize,
)]
#[serde(transparent)]
pub struct RichTextNodeCount(u32);

impl RichTextNodeCount {
    #[must_use]
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    #[must_use]
    pub const fn get(self) -> u32 {
        self.0
    }

    #[must_use]
    pub const fn as_usize(self) -> usize {
        self.0 as usize
    }

    #[must_use]
    pub const fn is_empty(self) -> bool {
        self.0 == 0
    }

    pub fn try_from_len(length: usize) -> Result<Self, RichTextNodeCountOverflow> {
        u32::try_from(length)
            .map(Self)
            .map_err(|_| RichTextNodeCountOverflow { length })
    }
}

impl From<RichTextNodeCount> for usize {
    fn from(value: RichTextNodeCount) -> Self {
        value.as_usize()
    }
}

impl TryFrom<usize> for RichTextNodeCount {
    type Error = RichTextNodeCountOverflow;

    fn try_from(value: usize) -> Result<Self, Self::Error> {
        Self::try_from_len(value)
    }
}

/// Failure to represent a host node count in the stable display-map wire.
#[derive(Clone, Copy, Debug, Error, Eq, PartialEq)]
#[error("rich-text node count {length} exceeds u32::MAX")]
pub struct RichTextNodeCountOverflow {
    pub length: usize,
}

/// Half-open preorder range containing a Ruby wrapper's descendants.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub struct RichTextNodeRange {
    pub start: RichTextNodeIndex,
    pub end: RichTextNodeIndex,
}

impl RichTextNodeRange {
    #[must_use]
    pub const fn new(start: RichTextNodeIndex, end: RichTextNodeIndex) -> Self {
        Self { start, end }
    }

    #[must_use]
    pub const fn is_empty(self) -> bool {
        self.start.get() == self.end.get()
    }

    #[must_use]
    pub fn contains(self, index: RichTextNodeIndex) -> bool {
        self.start <= index && index < self.end
    }

    #[must_use]
    pub const fn len(self) -> u32 {
        self.end.get().saturating_sub(self.start.get())
    }
}

/// Half-open range of indices into [`RichTextDisplayMap::text_runs`].
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub struct RichTextTextRunRange {
    pub start: u32,
    pub end: u32,
}

impl RichTextTextRunRange {
    #[must_use]
    pub const fn new(start: u32, end: u32) -> Self {
        Self { start, end }
    }

    #[must_use]
    pub const fn is_empty(self) -> bool {
        self.start == self.end
    }

    #[must_use]
    pub const fn contains(self, index: u32) -> bool {
        self.start <= index && index < self.end
    }

    #[must_use]
    pub const fn len(self) -> u32 {
        self.end.saturating_sub(self.start)
    }

    #[must_use]
    pub fn as_usize_range(self) -> std::ops::Range<usize> {
        self.start as usize..self.end as usize
    }
}

/// Half-open UTF-8 byte range.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextRange {
    pub start: usize,
    pub end: usize,
}

impl RichTextRange {
    #[must_use]
    pub const fn new(start: usize, end: usize) -> Self {
        Self { start, end }
    }
}

/// One resolved visible text run.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextTextRun {
    pub range: RichTextRange,
    pub source: RichTextTextSource,
    pub node_index: RichTextNodeIndex,
    pub styles: Vec<RichTextStyle>,
    #[serde(default)]
    pub presentation: RichTextPresentation,
}

/// Source category for a resolved visible text run.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum RichTextTextSource {
    Text,
    Interpolation,
    InterpolationFallback,
    ControlHardBreak,
    Raw,
}

/// Ruby annotation attached to a resolved base text range and its exact
/// authored/body/run ownership intervals.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextRubyAnnotation {
    pub owner_node: RichTextNodeIndex,
    pub body_nodes: RichTextNodeRange,
    pub base_runs: RichTextTextRunRange,
    pub base_range: RichTextRange,
    pub ruby: String,
    pub styles: Vec<RichTextStyle>,
    #[serde(default)]
    pub presentation: RichTextPresentation,
}

/// Control node marker in the resolved display stream.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextControlMarker {
    pub node_index: RichTextNodeIndex,
    /// UTF-8 byte offset immediately before this control executes.
    pub text_offset: usize,
    pub control: RichTextControl,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub range: Option<RichTextRange>,
}

/// Host event marker in authored node order.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct RichTextHostEventMarker {
    pub node_index: RichTextNodeIndex,
    /// UTF-8 byte offset at which this event becomes reachable.
    pub text_offset: usize,
    pub event_index: usize,
    pub event: DialogueHostEvent,
}

/// One fully resolved, persistence-safe rich-text node.
///
/// Executable interpolation and condition slots are consumed by the resolver
/// and therefore cannot enter a display frame.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum ResolvedRichTextNode {
    Text {
        text: String,
    },
    Scope {
        style: Box<RichTextStyle>,
        body: Vec<ResolvedRichTextNode>,
    },
    Ruby {
        body: Vec<ResolvedRichTextNode>,
        ruby: String,
    },
    Raw {
        text: String,
    },
    /// A source interpolation discarded by its resolved failure policy.
    /// Keeping this node preserves the exact preorder cardinality of the
    /// resolved source tree without inventing display text.
    Omitted,
    Control {
        control: RichTextControl,
    },
    HostEvent {
        event: DialogueHostEvent,
    },
}

impl LineDisplayFrame {
    /// Returns each active typed Fx application once in authored scope order.
    pub fn fx_applications(&self) -> impl Iterator<Item = &FxApplication> {
        fn collect<'a>(
            styles: impl IntoIterator<Item = &'a RichTextStyle>,
            out: &mut Vec<&'a FxApplication>,
        ) {
            for style in styles {
                if let RichTextStyle::Fx { application } = style {
                    out.push(application);
                }
            }
        }

        fn collect_nodes<'a>(nodes: &'a [ResolvedRichTextNode], out: &mut Vec<&'a FxApplication>) {
            for node in nodes {
                match node {
                    ResolvedRichTextNode::Scope { style, body } => {
                        collect([style.as_ref()], out);
                        collect_nodes(body, out);
                    }
                    ResolvedRichTextNode::Ruby { body, .. } => collect_nodes(body, out),
                    ResolvedRichTextNode::Text { .. }
                    | ResolvedRichTextNode::Raw { .. }
                    | ResolvedRichTextNode::Omitted
                    | ResolvedRichTextNode::Control { .. }
                    | ResolvedRichTextNode::HostEvent { .. } => {}
                }
            }
        }

        let mut applications = Vec::new();
        collect(self.base_styles.iter(), &mut applications);
        collect_nodes(&self.nodes, &mut applications);
        applications.into_iter()
    }
}

#[cfg(test)]
mod serde_tests {
    use super::*;
    use crate::RichTextTextSource;

    fn frame() -> LineDisplayFrame {
        let text = "Hello".to_owned();
        LineDisplayFrame {
            line: RuntimeLineId::from_runtime_line_value("say.test.001")
                .expect("runtime line identity"),
            character: DialoguePresentationCharacter {
                id: CharacterId::try_new("character.alice").expect("character identity"),
                display_name: "Alice".to_owned(),
            },
            text_key: TextKey::try_new("text.test.001").expect("text key"),
            effective: CharacterDialoguePresentationConfig {
                view: ViewId::try_new("view.dialogue.test").expect("View identity"),
                voice: None,
                look: None,
                stage: None,
                portrait: None,
                focus: None,
                cleanup: None,
                source_locale: None,
                hooks: Vec::new(),
                inline_failure: InlineFailurePolicy::FailLine,
                custom: BTreeMap::new(),
                config_digest: RuntimeValueDigest::ZERO,
            },
            text,
            base_styles: Vec::new(),
            style_contributions: Vec::new(),
            nodes: vec![ResolvedRichTextNode::Text {
                text: "Hello".to_owned(),
            }],
            display_map: RichTextDisplayMap {
                source_node_count: RichTextNodeCount::new(1),
                text_runs: vec![RichTextTextRun {
                    range: RichTextRange::new(0, 5),
                    source: RichTextTextSource::Text,
                    node_index: RichTextNodeIndex::new(0),
                    styles: Vec::new(),
                    presentation: RichTextPresentation::default(),
                }],
                ..RichTextDisplayMap::default()
            },
            host_events: Vec::new(),
            inline_failures: Vec::new(),
            unresolved: Vec::new(),
            content: RuntimeDialogueContentValue::try_new(
                arcweft_core::effect::RuntimeArtifactFingerprint::try_from_bytes([1; 32])
                    .expect("fixture artifact"),
                arcweft_core::runtime_id::RuntimeDialogueContentTemplateId::from_zero_based(0)
                    .expect("fixture template"),
                arcweft_core::entry::RuntimeDialogueContentTemplateDigest::from_bytes([2; 32]),
                [],
            )
            .expect("fixture content"),
        }
    }

    #[test]
    fn line_display_frame_round_trips_the_final_typed_wire() {
        let frame = frame();
        frame.validate().expect("fixture is structurally valid");
        let encoded = serde_json::to_vec(&frame).expect("frame serializes");
        let decoded = serde_json::from_slice::<LineDisplayFrame>(&encoded)
            .expect("validated frame deserializes");
        assert_eq!(decoded, frame);
    }

    #[test]
    fn line_display_frame_wire_rejects_invalid_ranges_and_removed_flat_fields() {
        let mut invalid_range = serde_json::to_value(frame()).expect("frame serializes");
        invalid_range["display_map"]["text_runs"][0]["range"]["end"] = 100.into();
        assert!(serde_json::from_value::<LineDisplayFrame>(invalid_range).is_err());

        let mut removed_flat_field = serde_json::to_value(frame()).expect("frame serializes");
        removed_flat_field["callee"] = "alice".into();
        assert!(serde_json::from_value::<LineDisplayFrame>(removed_flat_field).is_err());
    }
}
