[package]
name = "arcweft-presentation"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arcweft-character = { path = "../arcweft-character" }
arcweft-id = { path = "../arcweft-id" }

[lints]
workspace = true
