[package]
name = "arcweft-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []

[dependencies]
arcweft-character.workspace = true
arcweft-manifest-model.workspace = true
arcweft-id = { workspace = true }
arcweft-interaction-model.workspace = true
arcweft-need = { workspace = true }
arcweft-source = { workspace = true }
blake3.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
arcweft-data = { workspace = true }
arcweft-codec-binary = { workspace = true }
arcweft-codec-cbor = { workspace = true }
arcweft-codec-json = { workspace = true }
arcweft-codec-msgpack = { workspace = true }
arcweft-serde-bridge = { workspace = true }
trybuild.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true
