[package]
name = "arcweft-runtime-host"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arcweft-adapter-context = { workspace = true }
arcweft-bundle = { workspace = true, default-features = true }
arcweft-core = { workspace = true }
arcweft-host-adapter = { workspace = true }
arcweft-id = { workspace = true }
arcweft-image = { workspace = true }
arcweft-interaction-model = { workspace = true }
arcweft-presentation = { workspace = true }
arcweft-runtime-accelerator = { workspace = true, default-features = true }
arcweft-resource-model = { workspace = true }
arcweft-runtime-scheduler = { workspace = true }
arcweft-view = { workspace = true }
num_cpus.workspace = true
rayon.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
arcweft-character = { workspace = true }
arcweft-dialogue = { workspace = true }
arcweft-render-text = { workspace = true }
arcweft-text-model = { workspace = true }
arcweft-runtime-plan = { workspace = true }
arcweft-source = { workspace = true }
serde_json.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true
