[package]
name = "arcweft-render-web"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[target.'cfg(target_arch = "wasm32")'.dependencies]
arcweft-render-wgpu = { workspace = true }
thiserror.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = ["console"] }
wgpu = { workspace = true, features = ["webgpu"] }
winit.workspace = true

[lints]
workspace = true
