[package]
name = "arcweft-player-text-input"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arcweft-presentation = { workspace = true }
thiserror.workspace = true

[dev-dependencies]
arcweft-id = { workspace = true }
arcweft-view = { workspace = true }

[lib]
path = "src/lib.rs"

[lints]
workspace = true
