[package]
name = "arcweft"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arcweft-adt = { path = "../arcweft-adt" }
arcweft-core = { path = "../arcweft-core" }
arcweft-dialogue = { path = "../arcweft-dialogue" }
arcweft-id = { path = "../arcweft-id" }
arcweft-memory = { path = "../arcweft-memory" }
arcweft-need = { path = "../arcweft-need" }
arcweft-presentation = { path = "../arcweft-presentation" }
arcweft-ref = { path = "../arcweft-ref" }
arcweft-source = { path = "../arcweft-source" }

[lib]
path = "src/lib.rs"

[lints]
workspace = true
