[package]
name = "arcweft"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arcweft-adt = { workspace = true }
arcweft-character = { workspace = true }
arcweft-character-view = { workspace = true }
arcweft-core = { workspace = true }
arcweft-dialogue = { workspace = true }
arcweft-id = { workspace = true }
arcweft-memory = { workspace = true }
arcweft-need = { workspace = true }
arcweft-presentation = { workspace = true }
arcweft-ref = { workspace = true }
arcweft-source = { workspace = true }

[lib]
path = "src/lib.rs"

[lints]
workspace = true
