[package]
name = "arcweft-codec-msgpack"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version = "0.1.0"
description = "MSGPACK codec adapter for Arcweft data."

[dependencies]
arcweft-data = { workspace = true }
rmp.workspace = true
rmpv.workspace = true

[lints]
workspace = true
