[package]
name = "arcweft-launch"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arcweft-dialogue = { workspace = true }
arcweft-id = { workspace = true }
arcweft-manifest-model.workspace = true
arcweft-source = { workspace = true }
arcweft-view = { workspace = true }
serde = { workspace = true, features = ["derive"] }
taplo = { version = "0.14.0", default-features = false }
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
