use super::support::*;

#[test]
fn parses_documented_hook_memo_and_parser_items() {
    let tree = parse_ok(
        r#"
hook @hook.choice_visible
on @choice.opening.listen
phase AfterLayout
when every_frame
priority 10
once
effects signal.choice_visible
{
    signal.set(@signal.choice_visible, true)
}

memo fn route_title(route: Ref<Flow>) -> String
scope = session
{
    registry.flow(route).title
}

pub parser parse_player_command: Parser<PlayerCommand, ParseError> {
    alt { "advance" => PlayerCommand.Advance }
}
"#,
    );

    let Item::Hook(hook) = &tree.items()[0] else {
        panic!("expected hook item");
    };
    assert!(hook.when().is_some());
    assert_eq!(hook.priority(), Some(10));
    assert!(hook.once());
    assert_eq!(hook.effects().len(), 1);
    assert!(matches!(
        hook.body_statements(),
        [Stmt::Expr {
            expr: Expr::Call { .. },
            ..
        }]
    ));

    let Item::MemoFn(memo) = &tree.items()[1] else {
        panic!("expected memo item");
    };
    assert!(memo.body_statements().is_empty());
    assert!(matches!(memo.body_value(), Some(Expr::Select(_))));

    let Item::Parser(parser) = &tree.items()[2] else {
        panic!("expected parser item");
    };
    assert!(parser.body_statements().is_empty());
    assert!(matches!(parser.body_value(), Some(Expr::NamedBlock { name, .. }) if name == "alt"));

    let hir = lower_to_hir(&tree).expect("hook, memo, and parser items lower");
    validate_typecheck_ready(&hir).expect("hook, memo, and parser bodies are structured");
}

#[test]
fn content_declaration_is_a_typed_entity() {
    let tree = parse_ok(
        r"
content chapter_two {
    roots = [
        @flow.chapter_two,
    ]
}

flow chapter_two {}
",
    );

    let hir = lower_to_hir(&tree).expect("content declarations lower");
    validate_typecheck_ready(&hir).expect("content declarations are typecheck-ready");
    typecheck_hir(&hir, &TypeCheckEnv::new()).expect("content declarations typecheck");

    assert!(hir.declarations().iter().any(|decl| {
        matches!(
            decl,
            HirTopLevelDecl::EntityDecl(item)
                if item.kind() == EntityDeclKind::Content
                    && item.id().body() == "content.chapter_two"
                    && item.content_body().is_some_and(|body| body.roots().len() == 1)
        )
    }));
    let registry = registry_from_hir(&hir);
    validate_hir_references(&hir, &registry).expect("content roots resolve");
}

#[test]
fn parses_proof_and_trusted_axiom_items_as_structured_declarations() {
    let tree = parse_ok(
        r#"
proof @proof.line_summary_to_flow {
    requires summary.lifetime >= 'line
    ensures summary.lifetime >= 'flow
    check no_lifetime_below(LineSummary, 'flow)
}

trusted axiom @axiom.resource_manifest_hashes {
    reason = "resource manifest hashes are generated by signed build tooling"
}
"#,
    );

    let Item::Proof(proof) = &tree.items()[0] else {
        panic!("expected proof item");
    };
    assert_eq!(proof.id().body(), "proof.line_summary_to_flow");
    assert!(proof.body().contains("check no_lifetime_below"));
    assert!(matches!(
        proof.clauses(),
        [
            ProofClause::Requires { .. },
            ProofClause::Ensures { lifetime_targets, .. },
            ProofClause::Check { .. },
        ] if lifetime_targets.iter().any(|target| target == "'flow")
    ));

    let Item::TrustedAxiom(axiom) = &tree.items()[1] else {
        panic!("expected trusted axiom item");
    };
    assert_eq!(axiom.id().body(), "axiom.resource_manifest_hashes");
    assert!(axiom.body().contains("reason"));

    let hir = lower_to_hir(&tree).expect("proof metadata lowers as declarations");
    assert!(matches!(
        &hir.declarations()[0],
        HirTopLevelDecl::Proof(item) if item.id().body() == "proof.line_summary_to_flow"
    ));
    assert!(matches!(
        &hir.declarations()[1],
        HirTopLevelDecl::TrustedAxiom(item) if item.id().body() == "axiom.resource_manifest_hashes"
    ));
}

#[test]
fn rejects_unknown_top_level_sigil_and_invalid_memo_option() {
    let errors = parse_errors(
        r"
@project_attribute(scope = scene)
fn route_title(route: Ref<Flow>) -> String {
    registry.flow(route).title
}

memo fn route_graph(root: Ref<Flow>) -> RouteGraph
cache session
{
    build_route_graph(root)
}
",
    );

    assert!(
        errors
            .iter()
            .any(|error| error.message() == "`@` does not start a top-level item")
    );
    assert!(errors.iter().any(|error| error.message().contains("cache")));
}

#[test]
fn rejects_old_hook_header_syntax() {
    let errors = parse_errors(
        r"
hook @hook.choice_click
for @choice.opening.listen
on input target PointerClick
phase = input.target
{
    stop_propagation
}
",
    );

    assert!(errors.iter().any(|error| error.message().contains("for")));
    assert!(
        errors
            .iter()
            .any(|error| error.message().contains("phase ="))
    );
    assert!(
        errors
            .iter()
            .any(|error| error.message().contains("on input target"))
    );
}

#[test]
fn parses_documented_adt_items() {
    let tree = parse_ok(
        r"
#[derive(Clone, Debug, Format, Serialize, Eq)]
pub enum GameEvent {
    StartGame,
    ChoiceSelected { id: Ref<ChoiceOption> },
    Detailed {
        id: Ref<ChoiceOption>,
        label: TextKey,
    },
}

pub struct SettingsInput {
    text_speed: f32,
    master_volume: f32,
}

pub type PlayerName = String
where len(self) >= 1
where len(self) <= 16
",
    );

    let Item::Enum(event) = &tree.items()[0] else {
        panic!("expected enum item");
    };
    assert_eq!(event.attrs().len(), 1);
    assert_eq!(event.attrs()[0].name(), "derive");
    assert_eq!(event.visibility(), Some(Visibility::Public));
    assert_eq!(event.name(), "GameEvent");
    assert_eq!(event.variants().len(), 3);
    assert_eq!(event.variants()[1].name(), "ChoiceSelected");
    assert_eq!(
        event.variants()[1].payload(),
        Some("{ id: Ref<ChoiceOption> }")
    );
    assert_eq!(event.variants()[2].name(), "Detailed");
    assert!(
        event.variants()[2]
            .payload()
            .is_some_and(|payload| payload.contains("label: TextKey"))
    );

    let Item::Struct(settings) = &tree.items()[1] else {
        panic!("expected struct item");
    };
    assert_eq!(settings.fields().len(), 2);
    assert_eq!(settings.fields()[0].name(), "text_speed");

    let Item::TypeAlias(alias) = &tree.items()[2] else {
        panic!("expected type alias item");
    };
    assert_eq!(alias.name(), "PlayerName");
    assert!(matches!(alias.target(), TypeRef::Path(path) if path == "String"));
    assert_eq!(alias.where_clauses().len(), 2);

    let hir = lower_to_hir(&tree).expect("syntax-only adt items do not block lowering");
    assert!(hir.flows().is_empty());
    assert!(matches!(
        hir.declarations(),
        [
            HirTopLevelDecl::Enum(_),
            HirTopLevelDecl::Struct(_),
            HirTopLevelDecl::TypeAlias(_)
        ]
    ));
}

#[test]
fn parses_surface_alias_and_resource_entity_families() {
    let tree = parse_ok(
        r#"
pub asset bg.room {
    file = "bg/room.png"
    kind = image
}

pub image @image.sample.pulse {
    asset = @asset:.bg.room
    x = 12px
    y = 34px
    width = 56px
    height = 78px
}

pub character @character.alice Alice as alice {
}

pub voice profile @voice.alice.tts {
}

pub audio bus @bus.voice {
}

pub mixer snapshot @mix.dialogue {
}

pub ducking @duck.voice_over_bgm {
}

pub motion @motion.alice.nod {
}

pub rig @rig.alice.live2d {
}
"#,
    );

    assert!(matches!(
        &tree.items()[0],
        Item::EntityDecl(item) if item.kind() == EntityDeclKind::Asset
            && item.id().body() == "asset.bg.room"
            && item.body().is_some()
    ));
    assert!(matches!(
        &tree.items()[1],
        Item::EntityDecl(item) if item.kind() == EntityDeclKind::Image
            && item.id().body() == "image.sample.pulse"
            && item.image_body().is_some()
    ));
    let Item::EntityDecl(character) = &tree.items()[2] else {
        panic!("expected character declaration");
    };
    assert_eq!(character.kind(), EntityDeclKind::Character);
    assert_eq!(character.surface_alias(), Some("alice"));
    assert!(matches!(
        &tree.items()[3],
        Item::EntityDecl(item) if item.kind() == EntityDeclKind::Voice
    ));
    assert!(matches!(
        &tree.items()[4],
        Item::EntityDecl(item) if item.kind() == EntityDeclKind::AudioBus
    ));
    assert!(matches!(
        &tree.items()[5],
        Item::EntityDecl(item) if item.kind() == EntityDeclKind::MixerSnapshot
    ));
}

#[test]
fn parses_canonical_bare_entity_decl_name() {
    let tree = parse_ok(
        r#"
pub character alice {
    display = "Alice"
}
"#,
    );

    let Item::EntityDecl(character) = &tree.items()[0] else {
        panic!("expected character declaration");
    };
    assert_eq!(character.kind(), EntityDeclKind::Character);
    assert_eq!(character.id().body(), "character.alice");
    assert_eq!(character.name(), None);
    assert_eq!(character.surface_alias(), None);
}

#[test]
fn function_signatures_keep_default_parameters() {
    let signature =
        parse_fn_signature("fn fade(time: Duration = 120ms, easing: Ease = quad.out) -> Unit")
            .expect("signature with defaults parses");
    let params = signature.param_groups()[0].params();
    assert!(params[0].default().is_some());
    assert!(params[1].default().is_some());
}

#[test]
fn function_rest_parameters_bind_vec_and_check_call_arity() {
    let tree = parse_ok(
        r#"
fn log(message: String, fields: ...String) -> Unit {
    let copied: Vec<String> = fields
}

fn fixed(a: String, b: String) -> Unit {
}

flow @flow.ok ok {
    let fields: Vec<String> = ["asset", "elapsed"]
    log("loaded", "asset", "elapsed")
    log("loaded", fields...)
    fixed("one", ["two"]...)
}
"#,
    );
    let hir = lower_to_hir(&tree).expect("rest parameter function lowers");
    typecheck_hir(&hir, &TypeCheckEnv::new()).expect("rest parameters typecheck as Vec<T>");

    let bad_tree = parse_ok(
        r#"
fn fixed(a: String, b: String) -> Unit {
}

fn variadic(prefix: String, fields: ...String) -> Unit {
}

flow @flow.bad bad {
    let dynamic: Vec<String> = ["two"]
    fixed("one")
    fixed("one", "two", "three")
    fixed("one", dynamic...)
    variadic("ok", 1i32)
    variadic("ok", "bad"...)
    variadic(prefix = "ok", fields = "named")
}
"#,
    );
    let bad_hir = lower_to_hir(&bad_tree).expect("invalid rest call fixture still lowers");
    let errors = typecheck_hir(&bad_hir, &TypeCheckEnv::new())
        .expect_err("arity and rest argument issues are rejected");
    let messages = errors
        .iter()
        .map(|error| error.message().to_owned())
        .collect::<Vec<_>>();

    assert!(
        messages
            .iter()
            .any(|message| message.contains("missing required argument `b`")),
        "expected missing fixed argument diagnostic, got {messages:?}"
    );
    assert!(
        messages
            .iter()
            .any(|message| message.contains("too many positional arguments")),
        "expected too many argument diagnostic, got {messages:?}"
    );
    assert!(
        messages
            .iter()
            .any(|message| message.contains("must have type String")),
        "expected rest item type diagnostic, got {messages:?}"
    );
    assert!(
        messages
            .iter()
            .any(|message| message.contains("rest parameter `fields` is positional-only")),
        "expected named rest diagnostic, got {messages:?}"
    );
    assert!(
        messages
            .iter()
            .any(|message| message.contains("does not accept spread arguments")),
        "expected non-variadic spread diagnostic, got {messages:?}"
    );
    assert!(
        messages
            .iter()
            .any(|message| message.contains("spread argument must have sequence type")),
        "expected non-sequence spread diagnostic, got {messages:?}"
    );
}

#[test]
fn parses_anonymous_sum_type_refs_and_rejects_variant_rows() {
    let choice = parse_type_ref("Result<Payload, FsError | ParseError>")
        .expect("anonymous sum in generic argument parses");
    assert!(matches!(
        choice,
        TypeRef::Generic { base, args }
            if base == "Result"
                && matches!(args.as_slice(), [_, TypeRef::Choice(alternatives)] if alternatives.len() == 2)
    ));

    let rest_signature =
        parse_fn_signature("fn log(message: String, fields: ...(String | i64 | Duration)) -> Unit")
            .expect("rest parameter choice parses");
    let rest = &rest_signature.param_groups()[0].params()[1];
    assert!(rest.is_rest());
    assert!(matches!(
        rest.ty(),
        TypeRef::Choice(alternatives) if alternatives.len() == 3
    ));

    let duplicate = parse_type_ref("String | String").expect_err("duplicate branch is rejected");
    assert!(
        duplicate
            .to_string()
            .contains("duplicate alternative `String`")
    );

    let rows = parse_type_ref("Text(String) | Binary(Bytes)")
        .expect_err("variant rows are not anonymous sums");
    assert!(rows.to_string().contains("not variant rows"));
}

#[test]
fn anonymous_sum_typechecking_injects_joins_and_checks_exhaustiveness() {
    let tree = parse_ok(
        r#"
fn payload(flag: bool) -> String | Bytes {
    if flag { "text" } else { bytes }
}

fn log(message: String, fields: ...(String | i64 | Duration)) -> Unit {
}

flow @flow.ok ok(flag: bool) {
    let body: String | Bytes = "hello"
    let joined = payload(flag)
    let fields: Vec<String | i64 | Duration> = ["asset", 3i64, 120ms]
    let label = match body {
        text: String => text
        raw: Bytes => "bytes"
    }
    let fallback = match body {
        text: String => text
        _ => "bytes"
    }
    let captured = match body {
        value => "captured"
    }
    log("loaded", "asset", 3i64, 120ms)
    log("loaded", fields...)
}
"#,
    );
    let hir = lower_to_hir(&tree).expect("anonymous sum fixture lowers");
    typecheck_hir(
        &hir,
        &TypeCheckEnv::new().with_symbol("bytes", TypeKind::Named("Bytes".to_owned())),
    )
    .expect("anonymous sum fixture typechecks");

    let missing = parse_ok(
        r#"
flow @flow.bad bad {
    let body: String | Bytes = "hello"
    let label = match body {
        text: String => text
    }
}
"#,
    );
    let missing_hir = lower_to_hir(&missing).expect("missing fixture lowers");
    let errors = typecheck_hir(&missing_hir, &TypeCheckEnv::new())
        .expect_err("anonymous sum match must be exhaustive");
    assert!(
        errors
            .iter()
            .any(|error| error.message().contains("non-exhaustive match"))
    );
}

#[test]
fn anonymous_sum_rejects_alias_collapse_and_numeric_ambiguity() {
    let aliases = parse_ok(
        r"
type Name = String
type Email = String
type Contact = Name | Email
",
    );
    let alias_hir = lower_to_hir(&aliases).expect("alias collapse fixture lowers");
    let alias_errors =
        typecheck_hir(&alias_hir, &TypeCheckEnv::new()).expect_err("alias collapse is rejected");
    assert!(
        alias_errors
            .iter()
            .any(|error| error.message().contains("erase to the same type"))
    );

    let numeric = parse_ok(
        r"
flow @flow.bad bad {
    let value: i32 | i64 = 1
}
",
    );
    let numeric_hir = lower_to_hir(&numeric).expect("numeric fixture lowers");
    let numeric_errors = typecheck_hir(&numeric_hir, &TypeCheckEnv::new())
        .expect_err("ambiguous numeric branch is rejected");
    assert!(numeric_errors.iter().any(|error| {
        error
            .message()
            .contains("unsuffixed integer literal requires an expected integer type")
    }));
}

#[test]
fn public_anonymous_sum_abi_is_linted_without_rejecting_module() {
    let tree = parse_ok(
        r#"
pub type Payload = String | Bytes

pub fn read_payload(path: VirtualPath) -> String | Bytes {
    "payload"
}

fn private_helper(value: String | Bytes) -> Unit {
}
"#,
    );
    let hir = lower_to_hir(&tree).expect("public anonymous sum fixture lowers");
    let report = analyze_types(&hir, &TypeCheckEnv::new());
    assert!(
        report.diagnostics.is_empty(),
        "anonymous sums in public ABI should lint, not fail: {:?}",
        report.diagnostics
    );
    assert!(report.warnings.iter().any(|warning| {
        matches!(
            warning.kind(),
            crate::diagnostics::TypeCheckWarningKind::PublicAbiAnonymousSum {
                context,
                type_ref,
            } if context == "public type alias `Payload`"
                && type_ref.contains("String")
                && type_ref.contains("Bytes")
        )
    }));
    assert!(report.warnings.iter().any(|warning| {
        matches!(
            warning.kind(),
            crate::diagnostics::TypeCheckWarningKind::PublicAbiAnonymousSum {
                context,
                type_ref,
            } if context == "public function `read_payload` return type"
                && type_ref.contains("String")
                && type_ref.contains("Bytes")
        )
    }));
    let warnings = report
        .warnings
        .iter()
        .map(crate::diagnostics::TypeCheckWarning::message)
        .collect::<Vec<_>>();
    assert!(
        warnings
            .iter()
            .any(|message| message.contains("public type alias `Payload`")),
        "expected public type alias warning, got {warnings:?}"
    );
    assert!(
        warnings
            .iter()
            .any(|message| message.contains("public function `read_payload` return type")),
        "expected public function return warning, got {warnings:?}"
    );
    assert!(
        warnings
            .iter()
            .all(|message| !message.contains("private_helper")),
        "private anonymous sum helper should not lint, got {warnings:?}"
    );
}

#[test]
fn parses_documented_state_reducer_and_function_items() {
    let tree = parse_ok(
        r"
pub state GameState {
    pub route: Ref<Flow> = @flow.opening
    pub config: Config = Config {}
    pub flags: OrderedSet<Flag> = {}
    pub affection: OrderedMap<Ref<Character>, i32> = {}
    pub current_bg: Option<ImageHandle> = None
}

pub reducer update(state: GameState, event: GameEvent) -> Result<Update<GameState>, GameError>
requires state_is_valid
{
    match event {
        _ => Ok(state.to_update())
    }
}

pub fn current_scene(state: GameState) -> bool {
    true
}
",
    );

    let Item::State(state) = &tree.items()[0] else {
        panic!("expected state item");
    };
    assert_eq!(state.visibility(), Some(Visibility::Public));
    assert_eq!(state.name(), "GameState");
    assert_eq!(state.fields().len(), 5);
    assert_eq!(state.fields()[0].visibility(), Some(Visibility::Public));
    assert_eq!(state.fields()[0].name(), "route");
    assert!(
        matches!(state.fields()[0].default(), Expr::EntityRef(entity) if entity.body() == "flow.opening")
    );
    assert!(matches!(
        state.fields()[1].default(),
        Expr::Record { path, fields } if path == "Config" && fields.is_empty()
    ));

    let Item::Callable(reducer) = &tree.items()[1] else {
        panic!("expected reducer item");
    };
    assert_eq!(reducer.kind(), CallableKind::Reducer);
    assert_eq!(reducer.name(), "update");
    assert!(reducer.signature_tail().contains("GameEvent"));
    assert_eq!(reducer.contracts().len(), 1);
    assert!(reducer.body().contains("match event"));
    assert!(reducer.body_statements().is_empty());
    assert!(matches!(reducer.body_value(), Some(Expr::Match { .. })));

    let Item::Function(function) = &tree.items()[2] else {
        panic!("expected function item");
    };
    assert_eq!(function.kind(), FunctionKind::Function);
    assert_eq!(function.signature().name(), "current_scene");
    assert!(function.body_statements().is_empty());
    assert!(matches!(
        function.body_value().map(AuthoredExpr::expr),
        Some(Expr::Literal(Literal::Bool(true)))
    ));

    let hir = lower_to_hir(&tree).expect("syntax-only state/callable items do not block HIR");
    assert!(hir.flows().is_empty());
    assert_eq!(hir.functions().len(), 1);
    validate_typecheck_ready(&hir).expect("state defaults lower without raw expressions");
    assert!(matches!(
        hir.declarations(),
        [HirTopLevelDecl::State(_), HirTopLevelDecl::Callable(_)]
    ));
}

#[test]
fn parses_documented_trait_and_impl_items() {
    let tree = parse_ok(
        r"
pub trait Mappable {
    type Item
    type Mapped<B>
    fn map<B>(self, f: Self::Item -> B) -> Self::Mapped<B>
}

pub trait Ord: Eq {}

pub impl<T> Mappable for Option<T> {
    type Item = T
    type Mapped<B> = Option<B>

    fn map<B>(self, f: T -> B) -> Option<B> {
        match self {
            Some(x) => Some(f(x)),
            None => None,
        }
    }
}
",
    );

    assert_mappable_trait(&tree.items()[0]);

    let Item::Trait(ord) = &tree.items()[1] else {
        panic!("expected second trait item");
    };
    assert_eq!(ord.supertraits(), &["Eq".to_owned()]);

    assert_mappable_impl(&tree.items()[2]);

    let hir = lower_to_hir(&tree).expect("syntax-only trait/impl items do not block HIR");
    assert!(hir.flows().is_empty());
    assert!(matches!(
        hir.declarations(),
        [
            HirTopLevelDecl::Trait(_),
            HirTopLevelDecl::Trait(_),
            HirTopLevelDecl::Impl(_)
        ]
    ));
}

fn assert_mappable_trait(item: &Item) {
    let Item::Trait(mappable) = item else {
        panic!("expected trait item");
    };
    assert_eq!(mappable.visibility(), Some(Visibility::Public));
    assert_eq!(mappable.name(), "Mappable");
    assert_eq!(mappable.members().len(), 3);
    assert!(matches!(
        &mappable.members()[0],
        TraitMember::AssociatedType { name, params, value: None }
            if name == "Item" && params.is_empty()
    ));
    assert!(matches!(
        &mappable.members()[1],
        TraitMember::AssociatedType { name, params, value: None }
            if name == "Mapped" && params == &["B".to_owned()]
    ));
    assert!(matches!(
        &mappable.members()[2],
        TraitMember::Function { signature, .. }
            if signature.name() == "map"
                && signature
                    .param_groups()
                    .first()
                    .and_then(|group| group.params().first())
                    .is_some_and(|param| ident_pattern(param.pattern(), "self"))
    ));
}

fn assert_mappable_impl(item: &Item) {
    let Item::Impl(impl_item) = item else {
        panic!("expected impl item");
    };
    assert_eq!(impl_item.visibility(), Some(Visibility::Public));
    assert_eq!(impl_item.generics(), Some("<T>"));
    assert_eq!(impl_item.trait_name(), Some("Mappable"));
    assert_eq!(impl_item.target(), "Option<T>");
    assert_eq!(impl_item.members().len(), 3);
    assert!(matches!(
        &impl_item.members()[0],
        ImplMember::AssociatedType { name, params, value }
            if name == "Item" && params.is_empty() && matches!(value, TypeRef::Path(path) if path == "T")
    ));
    assert!(matches!(
        &impl_item.members()[1],
        ImplMember::AssociatedType { name, params, value }
            if name == "Mapped"
                && params == &["B".to_owned()]
                && matches!(value, TypeRef::Generic { base, args } if base == "Option" && args.len() == 1)
    ));
    assert!(matches!(
        &impl_item.members()[2],
        ImplMember::Function {
            signature,
            body,
            body_statements,
            body_value,
        }
            if signature.name() == "map"
                && signature
                    .param_groups()
                    .first()
                    .and_then(|group| group.params().first())
                    .is_some_and(|param| ident_pattern(param.pattern(), "self"))
                && body.contains("match self")
                && body_statements.is_empty()
                && matches!(
                    body_value.as_deref().map(AuthoredExpr::expr),
                    Some(Expr::Match { .. })
                )
    ));
    assert!(impl_item.body().contains("Some(x)"));
}

#[test]
fn parses_lifetime_type_syntax_for_borrow_checks() {
    let borrowed_slice = parse_type_ref("&'asset [Rgba8]").expect("borrowed slice type parses");
    assert!(matches!(
        borrowed_slice,
        TypeRef::Ref {
            lifetime: Some(ref lifetime),
            inner,
        } if lifetime.name() == "asset" && matches!(inner.as_ref(), TypeRef::Slice(_))
    ));

    let option_borrow =
        parse_type_ref("Option<&'a ChoiceView>").expect("generic borrowed type parses");
    assert!(matches!(option_borrow, TypeRef::Generic { .. }));

    let signature =
        parse_fn_signature("fn first<'a>(xs: &'a [ChoiceView]) -> Option<&'a ChoiceView>")
            .expect("fn signature lifetimes parse");
    assert_eq!(signature.name(), "first");
    assert_eq!(
        signature.generic_params()[0]
            .as_lifetime()
            .expect("lifetime generic")
            .name(),
        "a"
    );
    assert!(ident_pattern(
        signature.param_groups()[0].params()[0].pattern(),
        "xs"
    ));
    assert!(signature.return_type().is_some());
}

#[test]
fn parses_and_typechecks_function_parameter_destructuring() {
    let signature = parse_fn_signature(
        "fn summarize(TruckResult { score, rank, .. }: TruckResult, [first, ..rest]: Vec<Route>) -> Unit",
    )
    .expect("destructured function parameters parse");
    assert!(matches!(
        signature.param_groups()[0].params()[0].pattern(),
        Pattern::Record { path: Some(path), fields, rest }
            if path == "TruckResult" && fields.len() == 2 && *rest
    ));
    assert!(matches!(
        signature.param_groups()[0].params()[1].pattern(),
        Pattern::BracketSeq { items, rest }
            if matches!(items.as_slice(), [Pattern::Ident(name)] if name == "first")
                && rest.as_deref() == Some("rest")
    ));

    let tree = parse_ok(
        r"
fn summarize(TruckResult { score, rank, .. }: TruckResult, [first, ..rest]: Vec<Route>) -> Unit {
    let _ = score
    let _ = rank
    let _ = first
    let _ = rest
}
",
    );
    let hir = lower_to_hir(&tree).expect("function parameter destructuring lowers");
    validate_typecheck_ready(&hir).expect("function parameter destructuring is typecheck-ready");
    typecheck_hir(&hir, &TypeCheckEnv::new()).expect("destructured parameters bind locals");
}

#[test]
fn parses_self_receiver_and_function_type_parameters() {
    let signature = parse_fn_signature("fn map<B>(self, f: Self::Item -> B) -> Self::Mapped<B>")
        .expect("trait method signature parses");
    assert_eq!(signature.name(), "map");
    assert!(ident_pattern(
        signature.param_groups()[0].params()[0].pattern(),
        "self"
    ));
    assert!(ident_pattern(
        signature.param_groups()[0].params()[1].pattern(),
        "f"
    ));
    assert!(
        matches!(signature.return_type(), Some(TypeRef::Generic { base, .. }) if base == "Self::Mapped")
    );
}

#[test]
fn parses_task_fn_as_structured_function_item() {
    let tree = parse_ok(
        r"
task fn load_opening_assets() -> ArcResult<OpeningAssets> {
    let bg = try await load_bg()
    Ok(OpeningAssets { bg })
}
",
    );

    let Item::Function(function) = &tree.items()[0] else {
        panic!("expected task function item");
    };
    assert_eq!(function.kind(), FunctionKind::Task);
    assert_eq!(function.signature().name(), "load_opening_assets");
    assert_eq!(
        function.signature_text(),
        "fn load_opening_assets() -> ArcResult<OpeningAssets>"
    );
    assert!(matches!(
        function.body_statements()[0],
        Stmt::Let {
            expr: Expr::Await {
                applies_try: true,
                ..
            },
            ..
        }
    ));
    assert!(matches!(
        function.body_value().map(AuthoredExpr::expr),
        Some(Expr::Call { callee, .. }) if matches!(callee.as_ref(), Expr::Path(path) if path == "Ok")
    ));

    let hir = lower_to_hir(&tree).expect("task function lowers");
    assert_eq!(hir.functions().len(), 1);
    assert_eq!(hir.functions()[0].kind(), FunctionKind::Task);
    validate_typecheck_ready(&hir).expect("task function body has structured expressions");
}

#[test]
fn top_level_function_items_do_not_block_hir_lowering() {
    let tree = parse_ok(
        r"
fn label<'a>(choice: &'a ChoiceView) -> &'a DisplayText {
    choice.label
}

flow @flow.opening opening {
    goto @flow.title
}
",
    );

    let hir = lower_to_hir(&tree).expect("function and flow lower");
    assert_eq!(hir.functions().len(), 1);
    assert_eq!(hir.functions()[0].name(), "label");
    assert_eq!(hir.flows().len(), 1);
    assert_eq!(hir.flows()[0].id().expect("flow id").body(), "flow.opening");
}

#[test]
fn tail_return_function_body_satisfies_return_type() {
    let tree = parse_ok(
        r"
fn score(base: i64, bonus: i64) -> i64 {
    let boosted = bonus + 2
    return if base >= 3 { base * boosted } else { boosted }
}
",
    );
    let hir = lower_to_hir(&tree).expect("function lowers");
    assert!(matches!(
        hir.functions()[0].statements().last(),
        Some(Stmt::Return {
            expr: Expr::If { .. },
            ..
        })
    ));

    typecheck_hir(&hir, &TypeCheckEnv::default())
        .expect("tail return if expression supplies function body type");
}

#[test]
fn declaration_relative_ids_normalize_to_their_decl_family() {
    let tree = parse_ok(
        r"
character @.alice {}

character @. bob {}

signal @signal:.current_flow: Watch<Ref<Flow>>

signal @signal:. ready: Watch<bool>

hook @.choice_visible {
    on choice.visible
    phase after
}

dialogue defaults @dialogue:.opening {
    view = @view.side
}

source @source:.events() {
    yield event
}

source @source:. metrics() {
    yield event
}
",
    );
    let hir = lower_to_hir(&tree).expect("relative declaration ids lower");

    assert!(matches!(
        &hir.declarations()[0],
        HirTopLevelDecl::EntityDecl(item) if item.id().body() == "character.alice"
    ));
    assert!(matches!(
        &hir.declarations()[1],
        HirTopLevelDecl::EntityDecl(item) if item.id().body() == "character.bob"
    ));
    assert!(matches!(
        &hir.declarations()[2],
        HirTopLevelDecl::EntityDecl(item) if item.id().body() == "signal.current_flow"
    ));
    assert!(matches!(
        &hir.declarations()[3],
        HirTopLevelDecl::EntityDecl(item) if item.id().body() == "signal.ready"
    ));
    assert!(matches!(
        &hir.declarations()[4],
        HirTopLevelDecl::Hook(item) if item.id().body() == "hook.choice_visible"
    ));
    assert!(matches!(
        &hir.declarations()[5],
        HirTopLevelDecl::DialogueDefaults(item) if item.id().is_some_and(|id| id.body() == "dialogue.opening")
    ));
    assert!(matches!(
        &hir.declarations()[6],
        HirTopLevelDecl::Source(item) if item.id().is_some_and(|id| id.body() == "source.events")
    ));
    assert!(matches!(
        &hir.declarations()[7],
        HirTopLevelDecl::Source(item) if item.id().is_some_and(|id| id.body() == "source.metrics")
    ));
}

#[test]
fn typechecks_structured_function_body_for_hir_readiness() {
    let tree = parse_ok(
        r"
fn load_score() -> Result<i32, ScoreError> {
    let score = read_score()?
    return Ok(score)
}
",
    );
    let hir = lower_to_hir(&tree).expect("function lowers");

    assert_eq!(hir.functions().len(), 1);
    assert!(matches!(
        hir.functions()[0].statements()[0],
        Stmt::Let {
            expr: Expr::Try { .. },
            ..
        }
    ));
    validate_typecheck_ready(&hir).expect("function body has structured expressions");

    let env = TypeCheckEnv::new().with_function(
        "read_score",
        TypeKind::Result {
            ok: Box::new(TypeKind::I32),
            error: Box::new(TypeKind::Named("ScoreError".to_owned())),
        },
    );
    typecheck_hir(&hir, &env).expect("function body typechecks");
}

#[test]
fn parses_lowers_and_typechecks_documented_source_item() {
    let tree = parse_ok(
        r#"
pub source @source.face_camera_frames: Source<VideoFrameHandle, CaptureError> {
    from capture.camera(@capture.face_camera)
    backpressure = latest
    replay = hash_only
    privacy = transient

    on item frame => yield frame
    on disconnected => {
        signal.set(@signal.camera_connected, false)
        log.info("camera disconnected")
    }
    on error e => log.warn("camera stream error {err:?}", err = e)
}
"#,
    );
    let Item::Source(source) = &tree.items()[0] else {
        panic!("expected source item");
    };
    assert!(source.id().is_some());
    assert!(source.signature_tail().contains("Source<VideoFrameHandle"));
    assert!(matches!(
        source.source_ty(),
        Some(TypeRef::Generic { base, args }) if base == "Source" && args.len() == 2
    ));
    assert!(source.headers().iter().any(|header| matches!(
        header,
        SourceHeader::Backpressure {
            policy: SourceBackpressurePolicy::Latest,
            ..
        }
    )));
    assert!(source.headers().iter().any(|header| matches!(
        header,
        SourceHeader::Replay {
            policy: SourceReplayPolicy::HashOnly,
            ..
        }
    )));
    assert!(source.headers().iter().any(|header| matches!(
        header,
        SourceHeader::Privacy {
            policy: SourcePrivacyPolicy::Transient,
            ..
        }
    )));
    assert!(source.handlers().iter().any(|handler| matches!(
        handler.event(),
        SourceEventPattern::Item(Pattern::Ident(name))
            if name == "frame" && matches!(handler.body(), [Stmt::Yield(_)])
    )));
    assert!(source.handlers().iter().any(|handler| matches!(
        handler.event(),
        SourceEventPattern::Disconnected
            if matches!(handler.body(), [Stmt::Expr { expr: _, .. }, Stmt::Expr { expr: _, .. }])
    )));

    let hir = lower_to_hir(&tree).expect("documented source item lowers");
    assert!(
        hir.declarations()
            .iter()
            .any(|decl| matches!(decl, HirTopLevelDecl::Source(_)))
    );
    validate_typecheck_ready(&hir).expect("source item is typecheck-ready");
    let env = TypeCheckEnv::new()
        .with_symbol("capture", TypeKind::Named("CaptureApi".to_owned()))
        .with_symbol("latest", TypeKind::Named("BackpressurePolicy".to_owned()))
        .with_symbol("hash_only", TypeKind::Named("ReplayPolicy".to_owned()))
        .with_symbol("transient", TypeKind::Named("PrivacyPolicy".to_owned()))
        .with_method(
            TypeKind::Named("CaptureApi".to_owned()),
            "camera",
            TypeKind::Named("CaptureStream".to_owned()),
        )
        .with_function("log.info", TypeKind::Unit)
        .with_function("log.warn", TypeKind::Unit);
    typecheck_hir(&hir, &env).expect("documented source item typechecks");
}

#[test]
fn typecheck_rejects_function_like_source_with_loop_yield_body() {
    let tree = parse_ok(
        r"
source camera_frames() -> Source<VideoFrame, CameraError> {
    loop {
        let frame = await camera.next_frame()
        yield frame
    }
}
",
    );
    let Item::Source(source) = &tree.items()[0] else {
        panic!("expected source item");
    };
    assert_eq!(source.name(), Some("camera_frames"));
    assert!(matches!(
        source.body_statements(),
        [Stmt::Loop { body }] if matches!(body.as_slice(), [Stmt::Let { .. }, Stmt::Yield(_)])
    ));

    let hir = lower_to_hir(&tree).expect("function-like source lowers");
    validate_typecheck_ready(&hir).expect("function-like source is typecheck-ready");
    let env = TypeCheckEnv::new()
        .with_symbol("camera", TypeKind::Named("Camera".to_owned()))
        .with_method(
            TypeKind::Named("Camera".to_owned()),
            "next_frame",
            TypeKind::Need {
                ready: Box::new(TypeKind::Named("VideoFrame".to_owned())),
                error: Box::new(TypeKind::Named("CameraError".to_owned())),
            },
        );
    let errors = typecheck_hir(&hir, &env).expect_err("function-like source is rejected");
    assert!(errors.iter().any(|error| {
        error
            .message()
            .contains("function-like `source name() -> Source<T, E>` is not canonical")
    }));
}

#[test]
fn typecheck_rejects_source_missing_policy_and_private_full_replay() {
    let tree = parse_ok(
        r"
pub source @source.bad: Source<Frame, CaptureError> {
    from capture.camera(@capture.face)
    replay = full
    privacy = private

    on item frame => yield frame
}
",
    );
    let hir = lower_to_hir(&tree).expect("bad source lowers to HIR");
    validate_typecheck_ready(&hir).expect("bad source stays structurally ready");
    let errors =
        typecheck_hir(&hir, &TypeCheckEnv::new()).expect_err("bad source policy is rejected");

    assert!(errors.iter().any(|error| {
        error
            .message()
            .contains("source is missing `backpressure` policy")
    }));
    assert!(errors.iter().any(|error| {
        error
            .message()
            .contains("`privacy = private` is incompatible with `replay = full`")
    }));
}

#[test]
fn typecheck_rejects_duplicate_source_headers() {
    let tree = parse_ok(
        r"
pub source @source.duplicate: Source<Frame, CaptureError> {
    from capture.camera(@capture.face)
    backpressure = latest
    replay = none
    privacy = transient
    privacy = recordable
}
",
    );
    let hir = lower_to_hir(&tree).expect("duplicate source lowers to HIR");

    let errors =
        typecheck_hir(&hir, &TypeCheckEnv::new()).expect_err("duplicate header is rejected");
    assert!(errors.iter().any(|error| {
        error
            .message()
            .contains("source header `privacy` may appear only once")
    }));
}

#[test]
fn typecheck_rejects_recovered_and_invalid_source_policy_values() {
    let tree = parse_ok(
        r"
pub source @source.missing_overflow: Source<Frame, CaptureError> {
    from capture.values()
    backpressure = bounded(capacity = 1)
    replay = none
    privacy = transient
}

pub source @source.unknown_overflow: Source<Frame, CaptureError> {
    from capture.values()
    backpressure = bounded(capacity = 1, overflow = legacy)
    replay = none
    privacy = transient
}

pub source @source.invalid_capacity: Source<Frame, CaptureError> {
    from capture.values()
    backpressure = bounded(capacity = 0, overflow = error)
    replay = legacy_replay
    privacy = legacy_privacy
}
",
    );
    let hir = lower_to_hir(&tree).expect("recovered source policies lower to HIR");

    let errors =
        typecheck_hir(&hir, &TypeCheckEnv::new()).expect_err("invalid policies are rejected");
    for expected in [
        "bounded source policy requires an `overflow` option",
        "unknown source overflow policy `legacy`",
        "bounded source capacity must be greater than zero",
        "unknown source replay policy `legacy_replay`",
        "unknown source privacy policy `legacy_privacy`",
    ] {
        assert!(
            errors
                .iter()
                .any(|error| error.message().contains(expected)),
            "missing semantic policy diagnostic: {expected}"
        );
    }
}

#[test]
fn typecheck_rejects_statements_outside_source_handlers() {
    let tree = parse_ok(
        r"
pub source @source.direct: Source<Frame, CaptureError> {
    from capture.values()
    backpressure = latest
    replay = none
    privacy = transient
    signal.set(@signal.ready, true)
}
",
    );
    let hir = lower_to_hir(&tree).expect("direct source statement lowers to HIR");

    let errors = typecheck_hir(&hir, &TypeCheckEnv::new())
        .expect_err("direct source statements are rejected");
    assert!(errors.iter().any(|error| {
        error
            .message()
            .contains("source body statements must be inside an `on` handler")
    }));
}

#[test]
fn typecheck_rejects_stream_fn_returning_source() {
    let tree = parse_ok(
        r"
stream fn camera_frames() -> Source<Frame, CaptureError> {
    yield next_frame()
}
",
    );
    let hir = lower_to_hir(&tree).expect("stream function lowers to HIR");
    let errors = typecheck_hir(&hir, &TypeCheckEnv::new())
        .expect_err("stream fn returning source is rejected");

    assert!(errors.iter().any(|error| {
        error
            .message()
            .contains("`stream fn camera_frames` must declare `-> Stream<T, E>`")
    }));
}

#[test]
fn parses_entity_declarations_used_by_presentation_docs() {
    let tree = parse_ok(
        r#"
pub signal @signal.microphone_level: Watch<f32>

pub character @character.alice Alice {
    role = main
    nameplate = visible
}

pub layer @layer.view.game: NativeView {
    phase = View
    z = 500
}

activity @activity.truck_game TruckGame {
    mode = embedded
}

action feedback.submit(value: String)

view @view.settings SettingsPanel(config: Binding<Config>) {
    Panel {
        Text("Settings")
    }
}
"#,
    );
    let kinds = tree
        .items()
        .iter()
        .map(|item| match item {
            Item::EntityDecl(item) => item.kind(),
            other => panic!("expected entity declaration, got {other:?}"),
        })
        .collect::<Vec<_>>();
    assert_eq!(
        kinds,
        [
            EntityDeclKind::Signal,
            EntityDeclKind::Character,
            EntityDeclKind::Layer,
            EntityDeclKind::Activity,
            EntityDeclKind::Action,
            EntityDeclKind::View,
        ]
    );

    let hir = lower_to_hir(&tree).expect("entity declarations lower");
    validate_typecheck_ready(&hir).expect("entity declarations are typecheck-ready");
    typecheck_hir(&hir, &TypeCheckEnv::new()).expect("entity declarations typecheck");

    let registry = registry_from_hir(&hir);
    validate_hir_references(&hir, &registry).expect("declaration ids register themselves");
}

#[test]
fn parses_bodyless_parser_declarations_from_docs() {
    let tree = parse_ok(
        r"
pub parser parse_player_command: Parser<PlayerCommand, ParseError>
pub parser parse_image_header<'a>: Parser<ImageHeader<'a>, ParseError>
",
    );
    assert_eq!(tree.items().len(), 2);
    for item in tree.items() {
        let Item::Parser(parser) = item else {
            panic!("expected parser declaration");
        };
        assert!(parser.body().is_empty());
        assert!(parser.body_statements().is_empty());
        assert!(parser.signature_tail().contains("Parser<"));
    }

    let hir = lower_to_hir(&tree).expect("bodyless parser declarations lower");
    validate_typecheck_ready(&hir).expect("bodyless parser declarations are typecheck-ready");
    typecheck_hir(&hir, &TypeCheckEnv::new()).expect("bodyless parser declarations typecheck");
}

#[test]
fn parses_extern_rust_module_declaration_from_docs() {
    let tree = parse_ok(
        r#"
extern rust mod mini_games.truck from crate "truck_game" {
    pub event TruckEvent
    pub type TruckResult
    pub fn score_to_rank(score: i32) -> Rank
    pub activity truck_game: Activity<TruckInput, TruckResult>
}
"#,
    );
    let Item::ExternMod(item) = &tree.items()[0] else {
        panic!("expected extern module item");
    };
    assert_eq!(item.abi(), "rust");
    assert_eq!(item.path(), "mini_games.truck");
    assert_eq!(item.source(), Some(r#"crate "truck_game""#));
    assert!(item.body().contains("pub activity truck_game"));
    assert!(matches!(
        item.members(),
        [
            ExternModMember::Type(_),
            ExternModMember::Type(_),
            ExternModMember::Function(function),
            ExternModMember::Activity(_),
        ] if function.signature().name() == "score_to_rank"
    ));

    let hir = lower_to_hir(&tree).expect("extern rust module lowers");
    assert!(matches!(
        hir.declarations(),
        [HirTopLevelDecl::ExternMod(_)]
    ));
    validate_typecheck_ready(&hir).expect("extern module is typecheck-ready");
    let errors =
        typecheck_hir(&hir, &TypeCheckEnv::new()).expect_err("extern module requires metadata");
    assert!(matches!(
        errors.first().map(crate::diagnostics::TypeCheckError::kind),
        Some(TypeCheckErrorKind::MissingRustPackageMetadata { package }) if package == "truck_game"
    ));

    let env = TypeCheckEnv::new()
        .with_rust_type_export("truck_game", "TruckEvent")
        .with_rust_type_export("truck_game", "TruckResult")
        .with_rust_function_export(
            "truck_game",
            "mini_games.truck.score_to_rank",
            FunctionSignature::new(
                TypeKind::Named("Rank".to_owned()),
                [FunctionParam::required("score", TypeKind::I32)],
            ),
        );
    typecheck_hir(&hir, &env).expect("extern module metadata matches declaration");
}
