use arcweft_lang_sema::types::EntityKind;

pub(crate) fn entity_kind_label(kind: &EntityKind) -> &str {
    match kind {
        EntityKind::Agent => "agent",
        EntityKind::Entry => "entry",
        EntityKind::Flow => "flow",
        EntityKind::Fragment => "fragment",
        EntityKind::Choice => "choice",
        EntityKind::ChoiceOption => "choice_option",
        EntityKind::Character => "character",
        EntityKind::Component => "component",
        EntityKind::Activity => "activity",
        EntityKind::Textbox => "textbox",
        EntityKind::DialogueLine => "dialogue_line",
        EntityKind::Text => "text",
        EntityKind::Content => "content",
        EntityKind::Input => "input",
        EntityKind::Button => "button",
        EntityKind::Style => "style",
        EntityKind::Asset => "asset",
        EntityKind::Image => "image",
        EntityKind::Animation => "animation",
        EntityKind::Capture => "capture",
        EntityKind::Hook => "hook",
        EntityKind::Signal => "signal",
        EntityKind::Metric => "metric",
        EntityKind::Scene => "scene",
        EntityKind::Source => "source",
        EntityKind::Test => "test",
        EntityKind::Bench => "bench",
        EntityKind::Layer => "layer",
        EntityKind::Voice => "voice",
        EntityKind::Se => "se",
        EntityKind::Bgm => "bgm",
        EntityKind::AudioBus => "audio_bus",
        EntityKind::MixerSnapshot => "mixer_snapshot",
        EntityKind::Ducking => "ducking",
        EntityKind::Motion => "motion",
        EntityKind::Rig => "rig",
        EntityKind::Slot => "slot",
        EntityKind::Target => "target",
        EntityKind::Other(value) => value.as_str(),
    }
}
