[package]
name = "arcweft-lang-sema"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arcweft-character = { workspace = true }
arcweft-core.workspace = true
arcweft-data.workspace = true
arcweft-dialogue.workspace = true
arcweft-id = { workspace = true }
arcweft-lang-hir = { workspace = true }
arcweft-lang-syntax = { workspace = true }
arcweft-presentation = { workspace = true }
arcweft-rich-text-schema.workspace = true
arcweft-rust-abi = { workspace = true }
arcweft-source = { workspace = true }
arcweft-view = { workspace = true }
blake3.workspace = true
thiserror.workspace = true

[lib]
path = "src/lib.rs"

[dev-dependencies]
serde.workspace = true
trybuild.workspace = true

[lints]
workspace = true
