//! Resolved dialogue display frame and source map.

use crate::{
    DialogueHostEvent, InlineFailurePolicy, InlineTextFailure, RichTextControl,
    RichTextPresentation, RichTextStyle, RichTextStyleContribution,
};
use arcweft_core::plan::RuntimeLineId;
use arcweft_presentation::fx::FxApplication;
use serde::{Deserialize, Serialize};

/// One resolved frame generated by a player adapter.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct LineDisplayFrame {
    pub line: RuntimeLineId,
    pub callee: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub speaker_label: Option<String>,
    pub text: String,
    pub base_styles: Vec<RichTextStyle>,
    pub default_inline_failure_policy: Option<InlineFailurePolicy>,
    #[serde(default)]
    pub style_contributions: Vec<RichTextStyleContribution>,
    pub nodes: Vec<crate::RichTextNode>,
    pub display_map: RichTextDisplayMap,
    pub host_events: Vec<DialogueHostEvent>,
    pub inline_failures: Vec<InlineTextFailure>,
    pub unresolved: Vec<String>,
}

/// Mapping from resolved display text back to authored rich-text nodes.
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextDisplayMap {
    pub text_runs: Vec<RichTextTextRun>,
    pub ruby_annotations: Vec<RichTextRubyAnnotation>,
    pub controls: Vec<RichTextControlMarker>,
    pub host_events: Vec<RichTextHostEventMarker>,
}

/// Half-open UTF-8 byte range.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextRange {
    pub start: usize,
    pub end: usize,
}

impl RichTextRange {
    #[must_use]
    pub const fn new(start: usize, end: usize) -> Self {
        Self { start, end }
    }
}

/// One resolved visible text run.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextTextRun {
    pub range: RichTextRange,
    pub source: RichTextTextSource,
    pub node_index: usize,
    pub styles: Vec<RichTextStyle>,
    #[serde(default)]
    pub presentation: RichTextPresentation,
}

/// Source category for a resolved visible text run.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum RichTextTextSource {
    Text,
    Interpolation,
    InterpolationFallback,
    RubyBase,
    ControlHardBreak,
    ControlRaw,
}

/// Ruby annotation attached to a resolved base text range.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextRubyAnnotation {
    pub base_range: RichTextRange,
    pub ruby: String,
    pub node_index: usize,
    pub styles: Vec<RichTextStyle>,
    #[serde(default)]
    pub presentation: RichTextPresentation,
}

/// Control node marker in the resolved display stream.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextControlMarker {
    pub node_index: usize,
    /// UTF-8 byte offset immediately before this control executes.
    pub text_offset: usize,
    pub control: RichTextControl,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub range: Option<RichTextRange>,
}

/// Host event marker in authored node order.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RichTextHostEventMarker {
    pub node_index: usize,
    /// UTF-8 byte offset at which this event becomes reachable.
    pub text_offset: usize,
    pub event_index: usize,
    pub event: DialogueHostEvent,
}

impl LineDisplayFrame {
    /// Returns each active typed Fx application once in authored style-start order.
    pub fn fx_applications(&self) -> impl Iterator<Item = &FxApplication> {
        self.base_styles
            .iter()
            .chain(self.nodes.iter().filter_map(|node| match node {
                crate::RichTextNode::StyleStart { style } => Some(style),
                _ => None,
            }))
            .filter_map(|style| match style {
                RichTextStyle::Fx { application } => Some(application),
                _ => None,
            })
    }
}
