[package]
name = "arcweft-render-wgpu"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arcweft-glyphon = { workspace = true }
arcweft-id = { workspace = true }
arcweft-layout.workspace = true
arcweft-presentation = { workspace = true }
arcweft-render-text = { workspace = true }
arcweft-text-layout = { workspace = true }
arcweft-view = { workspace = true }
bytemuck.workspace = true
glyphon.workspace = true
num-traits.workspace = true
serde.workspace = true
thiserror.workspace = true
wgpu.workspace = true

[dev-dependencies]
arcweft-core = { workspace = true }
arcweft-dialogue = { workspace = true }
pollster.workspace = true
wgpu = { workspace = true, features = ["dx12", "metal", "vulkan"] }

[lib]
path = "src/lib.rs"

[lints]
workspace = true
