[package]
name = "arcweft-tooling"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arcweft-lang-hir = { path = "../arcweft-lang-hir" }
arcweft-lang-sema = { path = "../arcweft-lang-sema" }
arcweft-lang-syntax = { path = "../arcweft-lang-syntax" }
arcweft-source = { path = "../arcweft-source" }
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true
